export const resources = {
  "zh-CN": { translation: {
    common: { auto: "跟随浏览器", language: "语言", loading: "页面加载中", helpLoading: "帮助加载中", collapse: "收起", expand: "展开", close: "关闭", retry: "重试", reload: "重新加载", add: "添加规则", delete: "删除", moveUp: "上移", moveDown: "下移", items: "{{count}} 项", refresh: "刷新" },
    navigation: { label: "主导航", home: "主页", tasks: "任务", performers: "演员", discover: "发现", stats: "统计", settings: "设置", help: "帮助" },
    settings: { title: "配置与系统", state: "当前状态", waiting: "等待后端返回设置数据", saving: "保存中...", tabs: { connections: "连接", ingest: "入库", automation: "自动化", system: "系统", logs: "日志", about: "关于" }, connections: { save: "保存 {{service}} 连接", saved: "{{service}} 设置已保存。", dashboardPassword: "Dashboard 密码", dashboardPasswordPlaceholder: "Jackett 管理界面登录密码", username: "用户名", password: "密码", defaultSavePath: "默认保存路径", defaultCategory: "默认分类", defaultTags: "默认标签" }, ingest: { saved: "入库设置已保存。", save: "保存入库设置", mode: "入库方式", pathMap: "路径映射", transfer: "文件交付", qbRoot: "qB 下载根目录", stashRoot: "Stash 媒体库根目录", action: "交付动作", copy: "复制", move: "移动", symlink: "符号链接", mojiDownloadRoot: "Moji 下载根目录", mojiLibraryRoot: "Moji 媒体库根目录", pathMapInfo: "Moji 只把任务里的 qB 下载路径翻译成 Stash 扫描路径，不直接搬运文件。", transferInfo: "Moji 先把 qB 下载路径翻译成自己的可操作源路径，再交付到媒体库，并把同一相对路径翻译成 Stash 扫描路径。", qbRootInfo: "填写 qBittorrent 视角下的下载根目录。任务里的 ContentPath / SavePath 会先基于这个根路径计算相对路径。", mojiDownloadInfo: "填写 Moji 视角下的下载根目录。TRANSFER 模式会把上一步得到的相对路径拼到这里，得到 Moji 实际读取的源路径。", mojiLibraryInfo: "填写 Moji 视角下的媒体库根目录。TRANSFER 模式会把相对路径拼到这里，得到 Moji 实际写入的交付目标。", stashInfo: "填写 Stash 视角下的媒体库根目录。无论使用 PATH_MAP 还是 TRANSFER，Moji 最终都会把相对路径拼到这里并通知 Stash 扫描。", actionInfo: "COPY 会保留下载区原文件，MOVE 会把文件迁移进媒体库，SYMLINK 会在媒体库里创建指向源文件的符号链接。目标已存在同名文件或链接时会直接失败。", useQbDefault: "使用 qB 默认下载目录", noQbDefault: "当前未配置 qB 默认下载目录", initializeWith: "使用 {{path}} 初始化 qB 下载根目录", selectStashRoot: "请选择 Stash 媒体库根目录", noStashRoot: "暂无可用媒体库路径", initTitle: "初始化 qB 下载根目录", emptyTitle: "qB 下载根目录当前为空", initQuestion: "是否使用 qB 默认下载目录 {{path}} 初始化？", useAndSave: "使用默认目录并保存", keepEmpty: "保持为空并保存" } },
    help: { title: "Markdown 帮助", navigation: "帮助文档" },
    automation: { behaviors: { download: "下载", review: "记录供复核", block: "拦截" }, ranges: { all: "所有时间", oneYear: "一年内", twoYears: "两年内", threeYears: "三年内", fiveYears: "五年内" }, policy: { summary: "独演：{{solo}}；2–{{max}} 人共演：{{group}}；总集：{{compilation}}；发行范围：{{range}}；无法可靠判断或日期不明确时仅记录。" }, rules: { names: { indexerPreference: "索引器偏好", titleMatch: "标题匹配", publishDate: "发布时间", titleSimilarity: "标题相似度", seeders: "Seeders", size: "Size", singleVideo: "Torrent 单视频优先", fileNameMatch: "Torrent 文件名匹配" }, enableLabel: "启用{{rule}}", summary: { noIndexers: "未配置索引器", noTitleRules: "未配置标题规则", titleRules: "{{count}} 条标题匹配规则", dateAsc: "按发布时间从旧到新", dateDesc: "按发布时间从新到旧", similarity: "按标题相似度优先", seedersAsc: "按 Seeders 从少到多", seedersDesc: "按 Seeders 从多到少", sizeAsc: "按 Size 从小到大", sizeDesc: "按 Size 从大到小", singleVideo: "命中单视频结构时优先", noFileRules: "未配置文件名规则", fileRules: "{{count}} 条文件名规则{{lock}}" } } },
    automationUi: { syncInterval: "任务进度同步间隔（秒）", pollInterval: "订阅轮询间隔（小时）", taskSync: "任务同步：{{state}}", poll: "订阅轮询：{{state}}", enabled: "已启用", disabled: "未启用", policyTitle: "新发行下载策略", solo: "独演", soloInfo: "演员数为 1 时按这里的行为处理。", group: "共演", groupInfo: "演员数 2 到上限 N 的影片，以及超过 N 但未命中总集规则的影片，都按这里处理。", compilation: "总集", compilationInfo: "总集优先于独演和共演分类，优先根据标题、详情、标签和异常大的演员数判断。", groupMax: "共演人数上限", groupMaxInfo: "共演指演员数 2 到 N；超过 N 但未命中总集规则的影片，仍按共演处理。", dateRange: "自动下载时间范围", dateRangeInfo: "只在策略本来会自动下载时生效。超出范围或发行日期缺失的影片会改为记录供复核。", save: "保存自动化设置", saved: "自动化设置已保存。新的订阅发现将按此策略决定是否自动下载；已记录发行不回溯重判。", stashBoxes: { title: "Stash-Box 数据源优先级", detail: "在 Stash 中配置的 Stash-Box 会出现在这里。所有端点都会参与订阅查询，拖动卡片即可调整优先级。", refreshing: "刷新中...", refresh: "刷新", save: "保存优先级", saved: "Stash-Box 优先级已保存。", loading: "正在从 Stash 拉取 Stash-Box 端点…", loadingDetail: "这一过程由后端在启动时自动完成，请稍候。", empty: "Stash 中尚未配置任何 Stash-Box", emptyDetail: "请先在 Stash 中添加至少一个端点，再回到这里刷新列表。", loadFailed: "拉取失败：{{error}}", drag: "拖动以重新排序", keyReady: "API key 已配置", keyMissing: "未配置 API key", up: "上移", down: "下移" } },
    ruleUi: { title: "自动选种规则", detail: "默认仅影响后端自动挑选下载候选，规则按从上到下顺序依次比较。", save: "保存自动选种规则", saved: "自动选种规则已保存。", enableChain: "启用规则链", configured: "当前已配置 {{count}} 条规则，启用后才会生效。", drag: "拖动以重新排序", direction: "方向", similarityHint: "按查询词与标题的归一化相似度进行排序，不提供额外参数。", loadingIndexers: "加载索引器中…", noIndexers: "当前没有可用的 Jackett 索引器。", dragPriority: "拖动以调整优先级", titleHint: "按顺序匹配标题；PLAIN 为纯文本，REGEX 为正则，PREFER/AVOID 决定排序倾向。", noTitleRules: "尚未添加标题匹配规则。", titlePattern: "标题 Pattern", patternMode: "匹配模式", effect: "效果", inspectionIntro: "Torrent 文件结构精排固定在快速规则之后执行，只检查首轮排序后的前 {{count}} 个且带 .torrent 链接的候选。", inspectionScope: "检查范围", inspectionInfo: "仅作用于下方两条文件结构规则。值越大，第二阶段额外下载并解析种子文件的成本越高。", singleVideoHint: "只检查首轮排序后的前 {{count}} 个且带 .torrent 链接的候选；命中“单个视频文件”结构时优先。magnet 不参与文件结构检查。", fileHint: "按顺序匹配 torrent 内部文件路径或文件名", fileModeHint: "PLAIN 为纯文本，REGEX 为正则，LOCK 命中后直接选中。", noFileRules: "尚未添加文件名匹配规则。", filePattern: "Torrent 文件名 Pattern" },
    logsUi: { refreshing: "刷新中...", refresh: "刷新日志", copy: "复制当前列表", downloading: "下载中...", download: "下载当前日志", filter: "级别过滤：{{level}}", loaded: "已加载：{{count}}", state: "状态：{{state}}", syncing: "同步中", ready: "已就绪", source: "来源：当前日志文件", empty: "暂无日志", emptyDetail: "当前过滤条件下没有最近日志记录。", downloadHttpError: "下载失败：HTTP {{status}}", downloadFailed: "下载当前日志文件失败。" },
    systemUi: { saved: "系统设置已保存。", title: "系统", deletePolicy: "删除任务策略", deleteInfo: "控制删除 Moji 任务时，是否联动删除 qBittorrent 里的对应下载项，以及是否同时删除下载文件。", keep: "仅删除 Moji 任务记录", removeTorrent: "同时删除 qBittorrent 下载任务", removeFiles: "同时删除 qBittorrent 下载任务和文件", cache: "图片缓存", cacheInfo: "图片始终由 Moji 代理。关闭后仍会读取已有缓存，但新下载的图片不再写入磁盘。", enableCache: "启用图片缓存", maxSize: "缓存容量上限（MB）", maxSizeInfo: "允许 64–20480 MB；超过上限后按最近访问时间淘汰至上限的 90%。", retention: "缓存保留天数", retentionInfo: "允许 1–365 天；长期未访问的图片会被清理。", disabled: "磁盘持久化已关闭，以上配置暂不生效。", usage: "当前占用：{{size}}", images: "图片：{{count}} 张", cleanup: "最近清理：{{time}}", clearHint: "清空后保留图片来源登记，图片将在下次访问时自动重新下载。", clearing: "清理中...", noCache: "暂无缓存", clear: "清空图片缓存", clearTitle: "清空图片缓存？", clearDescription: "将删除 {{count}} 张本地图片并释放 {{size}}。来源登记会保留。", cancel: "取消", confirm: "确认清空", save: "保存系统设置", cleared: "图片缓存已清空。", clearedBytes: "图片缓存已清空，释放 {{size}}。", about: "关于", version: "版本" },
    errors: { notFoundTitle: "页面不存在", notFoundDetail: "这个地址没有对应的 Moji 页面。", returnHome: "返回主页", routeTitle: "页面加载失败", moduleLoad: "页面模块加载失败" },
    theme: { label: "主题：{{theme}}", choose: "选择主题", light: "浅色", dark: "深色", auto: "自动", resolved: "（当前显示：{{theme}}）" },
    stats: { title: "运行概览", loadFailed: "统计加载失败" },
    home: {
      services: "外部服务", ingestPolicy: "入库策略", todos: "待办任务", todosNote: "失败项、待扫描项和长时间停滞项都放在这里。",
      noTodos: "暂无待处理项", noTodosDetail: "这里会优先显示失败、待扫和异常任务。", configure: "去配置", adjust: "去调整", noData: "暂无数据", loadFailed: "首页加载失败", retryNoResult: "任务重试失败，后端没有返回任务记录。", retried: "已重试任务：{{task}}。",
      status: { unconfigured: "未配置", stale: "数据陈旧", enabled: "已启用", error: "运行异常", pending: "待检测", configuredDisabled: "已配置未启用" },
      diagnostics: {
        stashError: "已配置但最近未联通，请检查 Stash 服务状态。", stashMissing: "Stash 必须先配置，否则入库与演员更新流程无法展开。", stashPending: "Stash 已配置，等待首次探测或最近状态已过期。",
        jackettError: "已配置但最近未联通，请检查 Jackett 服务状态。", jackettMissing: "Jackett 必须先配置，否则任务搜索与演员更新没有上游数据。", jackettPending: "Jackett 已配置，等待首次探测或最近状态已过期。",
        qbError: "已配置但最近未联通，请检查 qBittorrent 服务状态。", qbMissing: "qBittorrent 必须先配置，否则下载与落地流程无法展开。", qbPending: "qBittorrent 已配置，等待首次探测或最近状态已过期。"
      },
      blockers: { jackettSearch: "任务搜索无索引源", jackettPerformers: "演员更新无上游数据", qbDownload: "任务无法启动下载", qbLanding: "下载完成后无客户端落地" },
      stats: { scenes: "{{count}} 部影片", stashMissing: "Stash 尚未回报数据", pendingScans: "Moji 待扫任务 {{count}} 项", indexers: "索引器 {{configured}} / {{total}} 已配置", slowest: "上次搜索最慢 {{latency}} ms", transfer: "下载 {{download}} · 上传 {{upload}}", active: "活跃任务 {{count}} · 连接 {{status}}" },
      config: { user: "用户", savePath: "保存路径", mode: "入库方式", action: "交付动作", qbRoot: "qB 下载根", mojiDownloadRoot: "Moji 下载根", mojiLibraryRoot: "Moji 媒体库根", stashRoot: "Stash 媒体库根" },
      ingest: { title: "入库", missing: "缺少：{{fields}}", incomplete: "工作方式已选择，但路径映射未填完整。", mode: "入库方式：{{mode}}", none: "未选择", pathMap: "路径映射", transfer: "文件交付", copy: "复制", move: "移动", symlink: "符号链接", guidePathMap: "Moji 只负责把 qB 下载路径翻译成 Stash 扫描路径，不直接搬运文件。", cautionPathMap: "要求先配置 qB 下载根路径和 Stash 媒体库根路径；两者使用各自命名空间。", guideTransfer: "Moji 先把 qB 下载路径翻译成自己的可操作路径，再交付到媒体库并换算为 Stash 扫描路径。", cautionTransfer: "要求同时配置 qB、Moji、Stash 三套根路径；目标已有同名文件或目录时会直接失败。", guideNone: "请选择入库策略后再继续。", blockerQb: "qB 下载根路径未映射", blockerStash: "Stash 媒体库根路径未映射", blockerScan: "任务完成后无法闭环换算扫描路径" }
    },
    tasks: {
      title: "工作台", metrics: "活跃 {{active}} · 完成 {{completed}} · 待扫 {{pendingScans}} · 失败 {{failed}}",
      searchPlaceholder: "搜索任务、番号、tracker、状态",
      filters: { all: "全部", running: "运行中", completed: "完成", failed: "失败", scanPending: "待扫描" },
      sorts: { createdAt: "最新", updatedAt: "更新时间", progress: "进度" },
      actions: { sync: "同步进度", scanAll: "触发扫描", scanGroup: "全部触发扫描", retryBlocked: "重试受阻任务", retryingBlocked: "正在重试受阻任务..." },
      empty: { title: "没有匹配的任务", detail: "换个过滤条件，或者先去发现区创建任务。" },
      groups: {
        attention: { label: "需处理", description: "失败、扫描报错或需要人工回看的任务。" },
        active: { label: "运行中", description: "仍在下载、同步或等待外部状态推进。" },
        ingestPending: { label: "待入库", description: "下载已完成，但 Stash 扫描尚未收口。" },
        completed: { label: "已完成", description: "流程已闭环的任务。" }
      }
    },
    taskRoute: { retryNoResult: "任务重试失败，后端没有返回任务记录。", retried: "已重试任务：{{task}}。", noneBlocked: "当前没有受阻任务需要重试。", retrySummary: "受阻任务重试完成：成功 {{succeeded}} 个，失败 {{failed}} 个。", deleteNoResult: "任务删除失败，后端没有返回已删除的任务记录。", deleted: "已删除任务：{{task}}。", loadFailed: "任务加载失败", resolutionTitle: "人工处理：{{task}}", task: "任务", details: "任务详情", loading: "正在加载任务...", notFound: "任务不存在", deleteTitle: "删除确认", confirmDelete: "确认删除任务", cancel: "取消", deleting: "删除中...", confirm: "确认删除" },
    taskUi: { noneSelected: "还没有选中任务", noneSelectedDetail: "点击任务卡片后，这里会显示详细信息和操作。", cannotResolve: "任务当前无法人工处理", cannotResolveDetail: "任务可能已经离开选种受阻阶段，请关闭后刷新任务列表。", resolution: { noResult: "后端没有返回已恢复的任务记录。", title: "人工解决选种受阻", detail: "为 {{code}} 重新搜索候选，或直接提供磁力链接以继续原任务。", magnetPlaceholder: "粘贴 magnet:?xt=urn:btih:...", magnetLabel: "磁力链接", submitting: "提交中...", useMagnet: "使用磁力链接", searching: "正在搜索...", searchAgain: "重新搜索候选", search: "搜索候选", found: "找到 {{count}} 个候选", none: "没有找到候选，可以修改 Jackett 配置后重搜，或直接粘贴磁力链接。", selecting: "选用中...", select: "选用" }, card: { aria: "{{task}}，状态：{{status}}，点击查看详情", resolveLabel: "人工处理任务：{{task}}", resolve: "人工处理", retryLabel: "重试任务：{{task}}", retrying: "重试中...", retry: "重试", scanLabel: "重扫任务：{{task}}", scanning: "扫描中...", scan: "重扫", deleteLabel: "删除任务：{{task}}", deleting: "删除中...", delete: "删除" } },
    titles: { tasks: "任务 · Moji", performers: "演员 · Moji", discover: "发现 · Moji", settings: "设置 · Moji", stats: "统计 · Moji", home: "Moji" }
  } },
  en: { translation: {
    common: { auto: "Use browser language", language: "Language", loading: "Loading page", helpLoading: "Loading help", collapse: "Collapse", expand: "Expand", close: "Close", retry: "Retry", reload: "Reload", add: "Add rule", delete: "Delete", moveUp: "Move up", moveDown: "Move down", items: "{{count}} item", items_other: "{{count}} items", refresh: "Refresh" },
    navigation: { label: "Main navigation", home: "Home", tasks: "Tasks", performers: "Performers", discover: "Discover", stats: "Statistics", settings: "Settings", help: "Help" },
    settings: { title: "Configuration & system", state: "Current status", waiting: "Waiting for settings data from the server", saving: "Saving...", tabs: { connections: "Connections", ingest: "Ingest", automation: "Automation", system: "System", logs: "Logs", about: "About" }, connections: { save: "Save {{service}} connection", saved: "{{service}} settings saved.", dashboardPassword: "Dashboard password", dashboardPasswordPlaceholder: "Jackett administration password", username: "Username", password: "Password", defaultSavePath: "Default save path", defaultCategory: "Default category", defaultTags: "Default tags" }, ingest: { saved: "Ingest settings saved.", save: "Save ingest settings", mode: "Ingest mode", pathMap: "Path mapping", transfer: "File delivery", qbRoot: "qB download root", stashRoot: "Stash library root", action: "Delivery action", copy: "Copy", move: "Move", symlink: "Symbolic link", mojiDownloadRoot: "Moji download root", mojiLibraryRoot: "Moji library root", pathMapInfo: "Moji translates the task's qB path into a Stash scan path without moving files.", transferInfo: "Moji translates the qB path into a locally accessible source, delivers it to the library, and maps the same relative path to Stash.", qbRootInfo: "The download root from qBittorrent's perspective. ContentPath and SavePath are made relative to this root.", mojiDownloadInfo: "The download root from Moji's perspective. TRANSFER appends the relative path here to locate the readable source.", mojiLibraryInfo: "The media root from Moji's perspective. TRANSFER appends the relative path here to create the delivery destination.", stashInfo: "The media root from Stash's perspective. Both modes append the relative path here and request a Stash scan.", actionInfo: "COPY preserves the source, MOVE relocates it, and SYMLINK creates a library link. Delivery fails when the destination already exists.", useQbDefault: "Use qB default download directory", noQbDefault: "No qB default download directory is configured", initializeWith: "Initialize the qB download root with {{path}}", selectStashRoot: "Select a Stash library root", noStashRoot: "No library paths available", initTitle: "Initialize qB download root", emptyTitle: "The qB download root is empty", initQuestion: "Initialize it with qB's default directory, {{path}}?", useAndSave: "Use default and save", keepEmpty: "Keep empty and save" } },
    help: { title: "Markdown help", navigation: "Help documentation" },
    automation: { behaviors: { download: "Download", review: "Record for review", block: "Block" }, ranges: { all: "Any date", oneYear: "Within one year", twoYears: "Within two years", threeYears: "Within three years", fiveYears: "Within five years" }, policy: { summary: "Solo: {{solo}}; 2–{{max}} performers: {{group}}; compilation: {{compilation}}; release range: {{range}}; ambiguous classifications or dates are recorded for review." }, rules: { names: { indexerPreference: "Indexer preference", titleMatch: "Title matching", publishDate: "Publish date", titleSimilarity: "Title similarity", seeders: "Seeders", size: "Size", singleVideo: "Prefer single-video torrents", fileNameMatch: "Torrent filename matching" }, enableLabel: "Enable {{rule}}", summary: { noIndexers: "No indexers configured", noTitleRules: "No title rules configured", titleRules: "{{count}} title rule", titleRules_other: "{{count}} title rules", dateAsc: "Publish date, oldest first", dateDesc: "Publish date, newest first", similarity: "Prefer title similarity", seedersAsc: "Seeders, fewest first", seedersDesc: "Seeders, most first", sizeAsc: "Size, smallest first", sizeDesc: "Size, largest first", singleVideo: "Prefer matching single-video structures", noFileRules: "No filename rules configured", fileRules: "{{count}} filename rule{{lock}}", fileRules_other: "{{count}} filename rules{{lock}}" } } },
    automationUi: { syncInterval: "Task progress sync interval (seconds)", pollInterval: "Subscription polling interval (hours)", taskSync: "Task sync: {{state}}", poll: "Subscription polling: {{state}}", enabled: "Enabled", disabled: "Disabled", policyTitle: "New-release download policy", solo: "Solo", soloInfo: "Applies when the scene has one performer.", group: "Group", groupInfo: "Applies to scenes with 2 through N performers, and larger scenes that do not match the compilation rule.", compilation: "Compilation", compilationInfo: "Compilation classification takes precedence and uses title, details, tags, and unusually large casts.", groupMax: "Maximum group performers", groupMaxInfo: "Group means 2 through N performers; larger scenes remain group scenes unless identified as compilations.", dateRange: "Automatic download date range", dateRangeInfo: "Only applies when the policy would download. Older or undated releases are recorded for review.", save: "Save automation settings", saved: "Automation settings saved. New subscription discoveries will use this policy; recorded releases are not reevaluated.", stashBoxes: { title: "Stash-Box source priority", detail: "Stash-Box endpoints configured in Stash appear here. All endpoints participate in subscription queries; drag cards to change priority.", refreshing: "Refreshing...", refresh: "Refresh", save: "Save priority", saved: "Stash-Box priority saved.", loading: "Loading Stash-Box endpoints from Stash…", loadingDetail: "The server performs this automatically during startup. Please wait.", empty: "No Stash-Box endpoints are configured in Stash", emptyDetail: "Add at least one endpoint in Stash, then refresh this list.", loadFailed: "Load failed: {{error}}", drag: "Drag to reorder", keyReady: "API key configured", keyMissing: "API key not configured", up: "Move up", down: "Move down" } },
    ruleUi: { title: "Automatic torrent selection rules", detail: "These only affect automatic candidate selection. Rules are compared from top to bottom.", save: "Save automatic selection rules", saved: "Automatic selection rules saved.", enableChain: "Enable rule chain", configured: "{{count}} rule configured; enable the chain to apply it.", configured_other: "{{count}} rules configured; enable the chain to apply them.", drag: "Drag to reorder", direction: "Direction", similarityHint: "Sort by normalized similarity between the query and title; there are no additional parameters.", loadingIndexers: "Loading indexers…", noIndexers: "No Jackett indexers are available.", dragPriority: "Drag to change priority", titleHint: "Match titles in order. PLAIN is literal, REGEX is regular expression, and PREFER/AVOID controls ranking.", noTitleRules: "No title matching rules added.", titlePattern: "Title pattern", patternMode: "Pattern mode", effect: "Effect", inspectionIntro: "Torrent structure refinement runs after fast rules and inspects the first {{count}} candidates that provide a .torrent link.", inspectionScope: "Inspection scope", inspectionInfo: "Only affects the two structure rules below. Larger values download and parse more torrent files in the second phase.", singleVideoHint: "Inspect the first {{count}} candidates with a .torrent link and prefer a single-video structure. Magnet links are not inspected.", fileHint: "Match paths or filenames inside the torrent in order.", fileModeHint: "PLAIN is literal, REGEX is regular expression, and LOCK immediately selects a match.", noFileRules: "No filename matching rules added.", filePattern: "Torrent filename pattern" },
    logsUi: { refreshing: "Refreshing...", refresh: "Refresh logs", copy: "Copy current list", downloading: "Downloading...", download: "Download current log", filter: "Level filter: {{level}}", loaded: "Loaded: {{count}}", state: "Status: {{state}}", syncing: "Syncing", ready: "Ready", source: "Source: current log file", empty: "No logs", emptyDetail: "There are no recent entries for the current filter.", downloadHttpError: "Download failed: HTTP {{status}}", downloadFailed: "Failed to download the current log file." },
    systemUi: { saved: "System settings saved.", title: "System", deletePolicy: "Task deletion policy", deleteInfo: "Controls whether deleting a Moji task also removes its qBittorrent item and downloaded files.", keep: "Delete only the Moji task record", removeTorrent: "Also remove the qBittorrent task", removeFiles: "Also remove the qBittorrent task and files", cache: "Image cache", cacheInfo: "Images are always proxied by Moji. When disabled, existing cache entries remain readable but new images are not persisted.", enableCache: "Enable image cache", maxSize: "Cache size limit (MB)", maxSizeInfo: "Allowed range: 64–20480 MB. LRU cleanup reduces usage to 90% of the limit.", retention: "Cache retention days", retentionInfo: "Allowed range: 1–365 days. Images not accessed within this period are removed.", disabled: "Disk persistence is disabled, so these settings are currently inactive.", usage: "Current usage: {{size}}", images: "Images: {{count}}", cleanup: "Last cleanup: {{time}}", clearHint: "Source registrations remain after clearing; images download again on their next access.", clearing: "Clearing...", noCache: "No cached images", clear: "Clear image cache", clearTitle: "Clear image cache?", clearDescription: "Delete {{count}} local images and release {{size}}. Source registrations will remain.", cancel: "Cancel", confirm: "Confirm clear", save: "Save system settings", cleared: "Image cache cleared.", clearedBytes: "Image cache cleared, releasing {{size}}.", about: "About", version: "Version" },
    errors: { notFoundTitle: "Page not found", notFoundDetail: "There is no Moji page at this address.", returnHome: "Return home", routeTitle: "Page failed to load", moduleLoad: "Page module failed to load" },
    theme: { label: "Theme: {{theme}}", choose: "Choose theme", light: "Light", dark: "Dark", auto: "Automatic", resolved: "(Currently showing: {{theme}})" },
    stats: { title: "Runtime overview", loadFailed: "Statistics failed to load" },
    home: {
      services: "External services", ingestPolicy: "Ingest policy", todos: "Tasks requiring attention", todosNote: "Failed, pending-scan, and stalled tasks appear here.",
      noTodos: "Nothing requires attention", noTodosDetail: "Failed, pending-scan, and abnormal tasks are prioritized here.", configure: "Configure", adjust: "Adjust", noData: "No data", loadFailed: "Home failed to load", retryNoResult: "The retry failed because the server returned no task record.", retried: "Retried task: {{task}}.",
      status: { unconfigured: "Not configured", stale: "Stale data", enabled: "Enabled", error: "Runtime error", pending: "Pending check", configuredDisabled: "Configured but disabled" },
      diagnostics: {
        stashError: "Configured but recently unreachable. Check the Stash service.", stashMissing: "Configure Stash before using ingest and performer updates.", stashPending: "Stash is configured and waiting for its first check, or its status is stale.",
        jackettError: "Configured but recently unreachable. Check the Jackett service.", jackettMissing: "Configure Jackett to provide upstream data for task searches and performer updates.", jackettPending: "Jackett is configured and waiting for its first check, or its status is stale.",
        qbError: "Configured but recently unreachable. Check the qBittorrent service.", qbMissing: "Configure qBittorrent before downloads and delivery can run.", qbPending: "qBittorrent is configured and waiting for its first check, or its status is stale."
      },
      blockers: { jackettSearch: "No indexer source for task searches", jackettPerformers: "No upstream data for performer updates", qbDownload: "Tasks cannot start downloads", qbLanding: "No client can finish downloaded content" },
      stats: { scenes: "{{count}} scene", scenes_other: "{{count}} scenes", stashMissing: "Stash has not reported data", pendingScans: "{{count}} Moji task pending scan", pendingScans_other: "{{count}} Moji tasks pending scan", indexers: "{{configured}} / {{total}} indexers configured", slowest: "Slowest recent search: {{latency}} ms", transfer: "Download {{download}} · Upload {{upload}}", active: "{{count}} active task · {{status}}", active_other: "{{count}} active tasks · {{status}}" },
      config: { user: "User", savePath: "Save path", mode: "Ingest mode", action: "Delivery action", qbRoot: "qB download root", mojiDownloadRoot: "Moji download root", mojiLibraryRoot: "Moji library root", stashRoot: "Stash library root" },
      ingest: { title: "Ingest", missing: "Missing: {{fields}}", incomplete: "A workflow is selected, but its path mapping is incomplete.", mode: "Ingest mode: {{mode}}", none: "Not selected", pathMap: "Path mapping", transfer: "File delivery", copy: "Copy", move: "Move", symlink: "Symbolic link", guidePathMap: "Moji translates the qB download path into a Stash scan path without moving files.", cautionPathMap: "Configure both the qB download root and Stash library root; each uses its own namespace.", guideTransfer: "Moji translates the qB path into a local source, delivers it to the library, and then calculates the Stash scan path.", cautionTransfer: "Configure qB, Moji, and Stash roots. Delivery fails if the destination already contains the same file or directory.", guideNone: "Select an ingest policy to continue.", blockerQb: "qB download root is not mapped", blockerStash: "Stash library root is not mapped", blockerScan: "Completed tasks cannot resolve a scan path" }
    },
    tasks: {
      title: "Workspace", metrics: "Active {{active}} · Completed {{completed}} · Pending scans {{pendingScans}} · Failed {{failed}}",
      searchPlaceholder: "Search tasks, codes, trackers, or statuses",
      filters: { all: "All", running: "Running", completed: "Completed", failed: "Failed", scanPending: "Pending scan" },
      sorts: { createdAt: "Newest", updatedAt: "Recently updated", progress: "Progress" },
      actions: { sync: "Sync progress", scanAll: "Trigger scans", scanGroup: "Scan all", retryBlocked: "Retry blocked tasks", retryingBlocked: "Retrying blocked tasks..." },
      empty: { title: "No matching tasks", detail: "Try different filters or create a task from Discover." },
      groups: {
        attention: { label: "Needs attention", description: "Failed tasks, scan errors, and tasks requiring review." },
        active: { label: "Running", description: "Tasks downloading, syncing, or waiting for an external state change." },
        ingestPending: { label: "Pending ingest", description: "Downloads completed but the Stash scan has not finished." },
        completed: { label: "Completed", description: "Tasks whose workflows have completed." }
      }
    },
    taskRoute: { retryNoResult: "The retry failed because the server returned no task record.", retried: "Retried task: {{task}}.", noneBlocked: "There are no blocked tasks to retry.", retrySummary: "Blocked-task retry complete: {{succeeded}} succeeded and {{failed}} failed.", deleteNoResult: "Deletion failed because the server returned no deleted task record.", deleted: "Deleted task: {{task}}.", loadFailed: "Tasks failed to load", resolutionTitle: "Manual resolution: {{task}}", task: "Task", details: "Task details", loading: "Loading task...", notFound: "Task not found", deleteTitle: "Confirm deletion", confirmDelete: "Confirm task deletion", cancel: "Cancel", deleting: "Deleting...", confirm: "Confirm deletion" },
    taskUi: { noneSelected: "No task selected", noneSelectedDetail: "Select a task card to see its details and actions here.", cannotResolve: "This task cannot be resolved manually", cannotResolveDetail: "The task may have left the blocked sourcing stage. Close this panel and refresh the list.", resolution: { noResult: "The server returned no resumed task record.", title: "Resolve blocked sourcing manually", detail: "Search again for {{code}}, or provide a magnet link to continue the existing task.", magnetPlaceholder: "Paste magnet:?xt=urn:btih:...", magnetLabel: "Magnet link", submitting: "Submitting...", useMagnet: "Use magnet link", searching: "Searching...", searchAgain: "Search again", search: "Search candidates", found: "Found {{count}} candidate", found_other: "Found {{count}} candidates", none: "No candidates found. Update Jackett and search again, or paste a magnet link.", selecting: "Selecting...", select: "Select" }, card: { aria: "{{task}}, status: {{status}}. Open details.", resolveLabel: "Resolve task manually: {{task}}", resolve: "Resolve manually", retryLabel: "Retry task: {{task}}", retrying: "Retrying...", retry: "Retry", scanLabel: "Rescan task: {{task}}", scanning: "Scanning...", scan: "Rescan", deleteLabel: "Delete task: {{task}}", deleting: "Deleting...", delete: "Delete" } },
    titles: { tasks: "Tasks · Moji", performers: "Performers · Moji", discover: "Discover · Moji", settings: "Settings · Moji", stats: "Statistics · Moji", home: "Moji" }
  } }
} as const;
