// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package graphql

import (
	"context"
	"time"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type StashGraphQLClient interface {
	FindPerformerByID(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*FindPerformerByID, error)
	FindPerformers(ctx context.Context, performerFilter *PerformerFilterType, filter *FindFilterType, performerIds []int, ids []string, interceptors ...clientv2.RequestInterceptor) (*FindPerformers, error)
	AllPerformers(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*AllPerformers, error)
	FindScenes(ctx context.Context, sceneFilter *SceneFilterType, filter *FindFilterType, interceptors ...clientv2.RequestInterceptor) (*FindScenes, error)
	UpdatePerformerCustomFields(ctx context.Context, input PerformerUpdateInput, interceptors ...clientv2.RequestInterceptor) (*UpdatePerformerCustomFields, error)
	GetVersion(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetVersion, error)
	MetadataScan(ctx context.Context, input ScanMetadataInput, interceptors ...clientv2.RequestInterceptor) (*MetadataScan, error)
	FindJob(ctx context.Context, input FindJobInput, interceptors ...clientv2.RequestInterceptor) (*FindJob, error)
	Configuration(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Configuration, error)
	FindSceneCount(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*FindSceneCount, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) StashGraphQLClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type StashIDFragment struct {
	Endpoint  string    "json:\"endpoint\" graphql:\"endpoint\""
	StashID   string    "json:\"stash_id\" graphql:\"stash_id\""
	UpdatedAt time.Time "json:\"updated_at\" graphql:\"updated_at\""
}

func (t *StashIDFragment) GetEndpoint() string {
	if t == nil {
		t = &StashIDFragment{}
	}
	return t.Endpoint
}
func (t *StashIDFragment) GetStashID() string {
	if t == nil {
		t = &StashIDFragment{}
	}
	return t.StashID
}
func (t *StashIDFragment) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &StashIDFragment{}
	}
	return &t.UpdatedAt
}

type PerformerFragment struct {
	ID             string             "json:\"id\" graphql:\"id\""
	Name           string             "json:\"name\" graphql:\"name\""
	Disambiguation *string            "json:\"disambiguation,omitempty\" graphql:\"disambiguation\""
	Gender         *GenderEnum        "json:\"gender,omitempty\" graphql:\"gender\""
	Birthdate      *string            "json:\"birthdate,omitempty\" graphql:\"birthdate\""
	Ethnicity      *string            "json:\"ethnicity,omitempty\" graphql:\"ethnicity\""
	Country        *string            "json:\"country,omitempty\" graphql:\"country\""
	EyeColor       *string            "json:\"eye_color,omitempty\" graphql:\"eye_color\""
	HeightCm       *int               "json:\"height_cm,omitempty\" graphql:\"height_cm\""
	Urls           []string           "json:\"urls,omitempty\" graphql:\"urls\""
	AliasList      []string           "json:\"alias_list\" graphql:\"alias_list\""
	Favorite       bool               "json:\"favorite\" graphql:\"favorite\""
	ImagePath      *string            "json:\"image_path,omitempty\" graphql:\"image_path\""
	SceneCount     int                "json:\"scene_count\" graphql:\"scene_count\""
	StashIds       []*StashIDFragment "json:\"stash_ids\" graphql:\"stash_ids\""
	Rating100      *int               "json:\"rating100,omitempty\" graphql:\"rating100\""
	CustomFields   map[string]any     "json:\"custom_fields\" graphql:\"custom_fields\""
}

func (t *PerformerFragment) GetID() string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.ID
}
func (t *PerformerFragment) GetName() string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Name
}
func (t *PerformerFragment) GetDisambiguation() *string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Disambiguation
}
func (t *PerformerFragment) GetGender() *GenderEnum {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Gender
}
func (t *PerformerFragment) GetBirthdate() *string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Birthdate
}
func (t *PerformerFragment) GetEthnicity() *string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Ethnicity
}
func (t *PerformerFragment) GetCountry() *string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Country
}
func (t *PerformerFragment) GetEyeColor() *string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.EyeColor
}
func (t *PerformerFragment) GetHeightCm() *int {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.HeightCm
}
func (t *PerformerFragment) GetUrls() []string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Urls
}
func (t *PerformerFragment) GetAliasList() []string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.AliasList
}
func (t *PerformerFragment) GetFavorite() bool {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Favorite
}
func (t *PerformerFragment) GetImagePath() *string {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.ImagePath
}
func (t *PerformerFragment) GetSceneCount() int {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.SceneCount
}
func (t *PerformerFragment) GetStashIds() []*StashIDFragment {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.StashIds
}
func (t *PerformerFragment) GetRating100() *int {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.Rating100
}
func (t *PerformerFragment) GetCustomFields() map[string]any {
	if t == nil {
		t = &PerformerFragment{}
	}
	return t.CustomFields
}

type StudioNameFragment struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *StudioNameFragment) GetID() string {
	if t == nil {
		t = &StudioNameFragment{}
	}
	return t.ID
}
func (t *StudioNameFragment) GetName() string {
	if t == nil {
		t = &StudioNameFragment{}
	}
	return t.Name
}

type SceneFragment struct {
	ID       string              "json:\"id\" graphql:\"id\""
	Title    *string             "json:\"title,omitempty\" graphql:\"title\""
	Code     *string             "json:\"code,omitempty\" graphql:\"code\""
	Date     *string             "json:\"date,omitempty\" graphql:\"date\""
	Urls     []string            "json:\"urls\" graphql:\"urls\""
	Studio   *StudioNameFragment "json:\"studio,omitempty\" graphql:\"studio\""
	Paths    SceneFragment_Paths "json:\"paths\" graphql:\"paths\""
	StashIds []*StashIDFragment  "json:\"stash_ids\" graphql:\"stash_ids\""
}

func (t *SceneFragment) GetID() string {
	if t == nil {
		t = &SceneFragment{}
	}
	return t.ID
}
func (t *SceneFragment) GetTitle() *string {
	if t == nil {
		t = &SceneFragment{}
	}
	return t.Title
}
func (t *SceneFragment) GetCode() *string {
	if t == nil {
		t = &SceneFragment{}
	}
	return t.Code
}
func (t *SceneFragment) GetDate() *string {
	if t == nil {
		t = &SceneFragment{}
	}
	return t.Date
}
func (t *SceneFragment) GetUrls() []string {
	if t == nil {
		t = &SceneFragment{}
	}
	return t.Urls
}
func (t *SceneFragment) GetStudio() *StudioNameFragment {
	if t == nil {
		t = &SceneFragment{}
	}
	return t.Studio
}
func (t *SceneFragment) GetPaths() *SceneFragment_Paths {
	if t == nil {
		t = &SceneFragment{}
	}
	return &t.Paths
}
func (t *SceneFragment) GetStashIds() []*StashIDFragment {
	if t == nil {
		t = &SceneFragment{}
	}
	return t.StashIds
}

type StashBoxFragment struct {
	Endpoint             string "json:\"endpoint\" graphql:\"endpoint\""
	APIKey               string "json:\"api_key\" graphql:\"api_key\""
	Name                 string "json:\"name\" graphql:\"name\""
	MaxRequestsPerMinute int    "json:\"max_requests_per_minute\" graphql:\"max_requests_per_minute\""
}

func (t *StashBoxFragment) GetEndpoint() string {
	if t == nil {
		t = &StashBoxFragment{}
	}
	return t.Endpoint
}
func (t *StashBoxFragment) GetAPIKey() string {
	if t == nil {
		t = &StashBoxFragment{}
	}
	return t.APIKey
}
func (t *StashBoxFragment) GetName() string {
	if t == nil {
		t = &StashBoxFragment{}
	}
	return t.Name
}
func (t *StashBoxFragment) GetMaxRequestsPerMinute() int {
	if t == nil {
		t = &StashBoxFragment{}
	}
	return t.MaxRequestsPerMinute
}

type SceneFragment_Paths struct {
	Screenshot *string "json:\"screenshot,omitempty\" graphql:\"screenshot\""
}

func (t *SceneFragment_Paths) GetScreenshot() *string {
	if t == nil {
		t = &SceneFragment_Paths{}
	}
	return t.Screenshot
}

type FindPerformers_FindPerformers struct {
	Count      int                  "json:\"count\" graphql:\"count\""
	Performers []*PerformerFragment "json:\"performers\" graphql:\"performers\""
}

func (t *FindPerformers_FindPerformers) GetCount() int {
	if t == nil {
		t = &FindPerformers_FindPerformers{}
	}
	return t.Count
}
func (t *FindPerformers_FindPerformers) GetPerformers() []*PerformerFragment {
	if t == nil {
		t = &FindPerformers_FindPerformers{}
	}
	return t.Performers
}

type FindScenes_FindScenes_Scenes_SceneFragment_Paths struct {
	Screenshot *string "json:\"screenshot,omitempty\" graphql:\"screenshot\""
}

func (t *FindScenes_FindScenes_Scenes_SceneFragment_Paths) GetScreenshot() *string {
	if t == nil {
		t = &FindScenes_FindScenes_Scenes_SceneFragment_Paths{}
	}
	return t.Screenshot
}

type FindScenes_FindScenes struct {
	Count  int              "json:\"count\" graphql:\"count\""
	Scenes []*SceneFragment "json:\"scenes\" graphql:\"scenes\""
}

func (t *FindScenes_FindScenes) GetCount() int {
	if t == nil {
		t = &FindScenes_FindScenes{}
	}
	return t.Count
}
func (t *FindScenes_FindScenes) GetScenes() []*SceneFragment {
	if t == nil {
		t = &FindScenes_FindScenes{}
	}
	return t.Scenes
}

type GetVersion_Version struct {
	BuildTime string  "json:\"build_time\" graphql:\"build_time\""
	Hash      string  "json:\"hash\" graphql:\"hash\""
	Version   *string "json:\"version,omitempty\" graphql:\"version\""
}

func (t *GetVersion_Version) GetBuildTime() string {
	if t == nil {
		t = &GetVersion_Version{}
	}
	return t.BuildTime
}
func (t *GetVersion_Version) GetHash() string {
	if t == nil {
		t = &GetVersion_Version{}
	}
	return t.Hash
}
func (t *GetVersion_Version) GetVersion() *string {
	if t == nil {
		t = &GetVersion_Version{}
	}
	return t.Version
}

type FindJob_FindJob struct {
	AddTime     time.Time  "json:\"addTime\" graphql:\"addTime\""
	Description string     "json:\"description\" graphql:\"description\""
	EndTime     *time.Time "json:\"endTime,omitempty\" graphql:\"endTime\""
	Error       *string    "json:\"error,omitempty\" graphql:\"error\""
	ID          string     "json:\"id\" graphql:\"id\""
	Progress    *float64   "json:\"progress,omitempty\" graphql:\"progress\""
	StartTime   *time.Time "json:\"startTime,omitempty\" graphql:\"startTime\""
	Status      JobStatus  "json:\"status\" graphql:\"status\""
	SubTasks    []string   "json:\"subTasks,omitempty\" graphql:\"subTasks\""
}

func (t *FindJob_FindJob) GetAddTime() *time.Time {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return &t.AddTime
}
func (t *FindJob_FindJob) GetDescription() string {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return t.Description
}
func (t *FindJob_FindJob) GetEndTime() *time.Time {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return t.EndTime
}
func (t *FindJob_FindJob) GetError() *string {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return t.Error
}
func (t *FindJob_FindJob) GetID() string {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return t.ID
}
func (t *FindJob_FindJob) GetProgress() *float64 {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return t.Progress
}
func (t *FindJob_FindJob) GetStartTime() *time.Time {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return t.StartTime
}
func (t *FindJob_FindJob) GetStatus() *JobStatus {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return &t.Status
}
func (t *FindJob_FindJob) GetSubTasks() []string {
	if t == nil {
		t = &FindJob_FindJob{}
	}
	return t.SubTasks
}

type Configuration_Configuration_General_Stashes struct {
	Path string "json:\"path\" graphql:\"path\""
}

func (t *Configuration_Configuration_General_Stashes) GetPath() string {
	if t == nil {
		t = &Configuration_Configuration_General_Stashes{}
	}
	return t.Path
}

type Configuration_Configuration_General struct {
	StashBoxes []*StashBoxFragment                            "json:\"stashBoxes\" graphql:\"stashBoxes\""
	Stashes    []*Configuration_Configuration_General_Stashes "json:\"stashes\" graphql:\"stashes\""
}

func (t *Configuration_Configuration_General) GetStashBoxes() []*StashBoxFragment {
	if t == nil {
		t = &Configuration_Configuration_General{}
	}
	return t.StashBoxes
}
func (t *Configuration_Configuration_General) GetStashes() []*Configuration_Configuration_General_Stashes {
	if t == nil {
		t = &Configuration_Configuration_General{}
	}
	return t.Stashes
}

type Configuration_Configuration struct {
	General Configuration_Configuration_General "json:\"general\" graphql:\"general\""
}

func (t *Configuration_Configuration) GetGeneral() *Configuration_Configuration_General {
	if t == nil {
		t = &Configuration_Configuration{}
	}
	return &t.General
}

type FindSceneCount_FindScenes struct {
	Count int "json:\"count\" graphql:\"count\""
}

func (t *FindSceneCount_FindScenes) GetCount() int {
	if t == nil {
		t = &FindSceneCount_FindScenes{}
	}
	return t.Count
}

type FindPerformerByID struct {
	FindPerformer *PerformerFragment "json:\"findPerformer,omitempty\" graphql:\"findPerformer\""
}

func (t *FindPerformerByID) GetFindPerformer() *PerformerFragment {
	if t == nil {
		t = &FindPerformerByID{}
	}
	return t.FindPerformer
}

type FindPerformers struct {
	FindPerformers FindPerformers_FindPerformers "json:\"findPerformers\" graphql:\"findPerformers\""
}

func (t *FindPerformers) GetFindPerformers() *FindPerformers_FindPerformers {
	if t == nil {
		t = &FindPerformers{}
	}
	return &t.FindPerformers
}

type AllPerformers struct {
	AllPerformers []*PerformerFragment "json:\"allPerformers\" graphql:\"allPerformers\""
}

func (t *AllPerformers) GetAllPerformers() []*PerformerFragment {
	if t == nil {
		t = &AllPerformers{}
	}
	return t.AllPerformers
}

type FindScenes struct {
	FindScenes FindScenes_FindScenes "json:\"findScenes\" graphql:\"findScenes\""
}

func (t *FindScenes) GetFindScenes() *FindScenes_FindScenes {
	if t == nil {
		t = &FindScenes{}
	}
	return &t.FindScenes
}

type UpdatePerformerCustomFields struct {
	PerformerUpdate *PerformerFragment "json:\"performerUpdate,omitempty\" graphql:\"performerUpdate\""
}

func (t *UpdatePerformerCustomFields) GetPerformerUpdate() *PerformerFragment {
	if t == nil {
		t = &UpdatePerformerCustomFields{}
	}
	return t.PerformerUpdate
}

type GetVersion struct {
	Version GetVersion_Version "json:\"version\" graphql:\"version\""
}

func (t *GetVersion) GetVersion() *GetVersion_Version {
	if t == nil {
		t = &GetVersion{}
	}
	return &t.Version
}

type MetadataScan struct {
	MetadataScan string "json:\"metadataScan\" graphql:\"metadataScan\""
}

func (t *MetadataScan) GetMetadataScan() string {
	if t == nil {
		t = &MetadataScan{}
	}
	return t.MetadataScan
}

type FindJob struct {
	FindJob *FindJob_FindJob "json:\"findJob,omitempty\" graphql:\"findJob\""
}

func (t *FindJob) GetFindJob() *FindJob_FindJob {
	if t == nil {
		t = &FindJob{}
	}
	return t.FindJob
}

type Configuration struct {
	Configuration Configuration_Configuration "json:\"configuration\" graphql:\"configuration\""
}

func (t *Configuration) GetConfiguration() *Configuration_Configuration {
	if t == nil {
		t = &Configuration{}
	}
	return &t.Configuration
}

type FindSceneCount struct {
	FindScenes FindSceneCount_FindScenes "json:\"findScenes\" graphql:\"findScenes\""
}

func (t *FindSceneCount) GetFindScenes() *FindSceneCount_FindScenes {
	if t == nil {
		t = &FindSceneCount{}
	}
	return &t.FindScenes
}

const FindPerformerByIDDocument = `query FindPerformerByID ($id: ID!) {
	findPerformer(id: $id) {
		... PerformerFragment
	}
}
fragment PerformerFragment on Performer {
	id
	name
	disambiguation
	gender
	birthdate
	ethnicity
	country
	eye_color
	height_cm
	urls
	alias_list
	favorite
	image_path
	scene_count
	stash_ids {
		... StashIdFragment
	}
	rating100
	custom_fields
}
fragment StashIdFragment on StashID {
	endpoint
	stash_id
	updated_at
}
`

func (c *Client) FindPerformerByID(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*FindPerformerByID, error) {
	vars := map[string]any{
		"id": id,
	}

	var res FindPerformerByID
	if err := c.Client.Post(ctx, "FindPerformerByID", FindPerformerByIDDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const FindPerformersDocument = `query FindPerformers ($performer_filter: PerformerFilterType, $filter: FindFilterType, $performer_ids: [Int!], $ids: [ID!]) {
	findPerformers(performer_filter: $performer_filter, filter: $filter, performer_ids: $performer_ids, ids: $ids) {
		count
		performers {
			... PerformerFragment
		}
	}
}
fragment PerformerFragment on Performer {
	id
	name
	disambiguation
	gender
	birthdate
	ethnicity
	country
	eye_color
	height_cm
	urls
	alias_list
	favorite
	image_path
	scene_count
	stash_ids {
		... StashIdFragment
	}
	rating100
	custom_fields
}
fragment StashIdFragment on StashID {
	endpoint
	stash_id
	updated_at
}
`

func (c *Client) FindPerformers(ctx context.Context, performerFilter *PerformerFilterType, filter *FindFilterType, performerIds []int, ids []string, interceptors ...clientv2.RequestInterceptor) (*FindPerformers, error) {
	vars := map[string]any{
		"performer_filter": performerFilter,
		"filter":           filter,
		"performer_ids":    performerIds,
		"ids":              ids,
	}

	var res FindPerformers
	if err := c.Client.Post(ctx, "FindPerformers", FindPerformersDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const AllPerformersDocument = `query allPerformers {
	allPerformers {
		... PerformerFragment
	}
}
fragment PerformerFragment on Performer {
	id
	name
	disambiguation
	gender
	birthdate
	ethnicity
	country
	eye_color
	height_cm
	urls
	alias_list
	favorite
	image_path
	scene_count
	stash_ids {
		... StashIdFragment
	}
	rating100
	custom_fields
}
fragment StashIdFragment on StashID {
	endpoint
	stash_id
	updated_at
}
`

func (c *Client) AllPerformers(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*AllPerformers, error) {
	vars := map[string]any{}

	var res AllPerformers
	if err := c.Client.Post(ctx, "allPerformers", AllPerformersDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const FindScenesDocument = `query FindScenes ($scene_filter: SceneFilterType, $filter: FindFilterType) {
	findScenes(scene_filter: $scene_filter, filter: $filter) {
		count
		scenes {
			... SceneFragment
		}
	}
}
fragment SceneFragment on Scene {
	id
	title
	code
	date
	urls
	studio {
		... StudioNameFragment
	}
	paths {
		screenshot
	}
	stash_ids {
		... StashIdFragment
	}
}
fragment StudioNameFragment on Studio {
	id
	name
}
fragment StashIdFragment on StashID {
	endpoint
	stash_id
	updated_at
}
`

func (c *Client) FindScenes(ctx context.Context, sceneFilter *SceneFilterType, filter *FindFilterType, interceptors ...clientv2.RequestInterceptor) (*FindScenes, error) {
	vars := map[string]any{
		"scene_filter": sceneFilter,
		"filter":       filter,
	}

	var res FindScenes
	if err := c.Client.Post(ctx, "FindScenes", FindScenesDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const UpdatePerformerCustomFieldsDocument = `mutation UpdatePerformerCustomFields ($input: PerformerUpdateInput!) {
	performerUpdate(input: $input) {
		... PerformerFragment
	}
}
fragment PerformerFragment on Performer {
	id
	name
	disambiguation
	gender
	birthdate
	ethnicity
	country
	eye_color
	height_cm
	urls
	alias_list
	favorite
	image_path
	scene_count
	stash_ids {
		... StashIdFragment
	}
	rating100
	custom_fields
}
fragment StashIdFragment on StashID {
	endpoint
	stash_id
	updated_at
}
`

func (c *Client) UpdatePerformerCustomFields(ctx context.Context, input PerformerUpdateInput, interceptors ...clientv2.RequestInterceptor) (*UpdatePerformerCustomFields, error) {
	vars := map[string]any{
		"input": input,
	}

	var res UpdatePerformerCustomFields
	if err := c.Client.Post(ctx, "UpdatePerformerCustomFields", UpdatePerformerCustomFieldsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetVersionDocument = `query GetVersion {
	version {
		hash
		build_time
		version
	}
}
`

func (c *Client) GetVersion(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetVersion, error) {
	vars := map[string]any{}

	var res GetVersion
	if err := c.Client.Post(ctx, "GetVersion", GetVersionDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const MetadataScanDocument = `mutation MetadataScan ($input: ScanMetadataInput!) {
	metadataScan(input: $input)
}
`

func (c *Client) MetadataScan(ctx context.Context, input ScanMetadataInput, interceptors ...clientv2.RequestInterceptor) (*MetadataScan, error) {
	vars := map[string]any{
		"input": input,
	}

	var res MetadataScan
	if err := c.Client.Post(ctx, "MetadataScan", MetadataScanDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const FindJobDocument = `query FindJob ($input: FindJobInput!) {
	findJob(input: $input) {
		id
		status
		description
		progress
		startTime
		endTime
		addTime
		error
		subTasks
	}
}
`

func (c *Client) FindJob(ctx context.Context, input FindJobInput, interceptors ...clientv2.RequestInterceptor) (*FindJob, error) {
	vars := map[string]any{
		"input": input,
	}

	var res FindJob
	if err := c.Client.Post(ctx, "FindJob", FindJobDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ConfigurationDocument = `query Configuration {
	configuration {
		general {
			stashes {
				path
			}
			stashBoxes {
				... StashBoxFragment
			}
		}
	}
}
fragment StashBoxFragment on StashBox {
	endpoint
	api_key
	name
	max_requests_per_minute
}
`

func (c *Client) Configuration(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Configuration, error) {
	vars := map[string]any{}

	var res Configuration
	if err := c.Client.Post(ctx, "Configuration", ConfigurationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const FindSceneCountDocument = `query FindSceneCount {
	findScenes(filter: {per_page:0}) {
		count
	}
}
`

func (c *Client) FindSceneCount(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*FindSceneCount, error) {
	vars := map[string]any{}

	var res FindSceneCount
	if err := c.Client.Post(ctx, "FindSceneCount", FindSceneCountDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	FindPerformerByIDDocument:           "FindPerformerByID",
	FindPerformersDocument:              "FindPerformers",
	AllPerformersDocument:               "allPerformers",
	FindScenesDocument:                  "FindScenes",
	UpdatePerformerCustomFieldsDocument: "UpdatePerformerCustomFields",
	GetVersionDocument:                  "GetVersion",
	MetadataScanDocument:                "MetadataScan",
	FindJobDocument:                     "FindJob",
	ConfigurationDocument:               "Configuration",
	FindSceneCountDocument:              "FindSceneCount",
}
