model:
  package: graphql
  filename: ./pkg/stashbox/graphql/generated_models.go
client:
  package: graphql
  filename: ./pkg/stashbox/graphql/generated_client.go
models:
  Date:
    model: github.com/99designs/gqlgen/graphql.String
endpoint:
  url: https://javstash.org/graphql
query:
- "./graphql/stashbox/*.graphql"
generate:
  clientV2: false
  clientInterfaceName: "StashBoxGraphQLClient"
