package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"math"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// FollowPerformer is the resolver for the followPerformer field.
func (r *mutationResolver) FollowPerformer(ctx context.Context, stashPerformerID string) (*model.FollowingPerformer, error) {
	if r.Following == nil {
		return nil, errors.New("following service is not configured")
	}

	item, err := r.Following.FollowPerformer(ctx, stashPerformerID)
	if err != nil {
		return nil, err
	}
	return followingPerformerToModel(item), nil
}

// UnfollowPerformer is the resolver for the unfollowPerformer field.
func (r *mutationResolver) UnfollowPerformer(ctx context.Context, stashPerformerID string) (bool, error) {
	if r.Following == nil {
		return false, errors.New("following service is not configured")
	}

	if err := r.Following.UnfollowPerformer(ctx, stashPerformerID); err != nil {
		return false, err
	}
	return true, nil
}

// RefreshFollowingPerformer is the resolver for the refreshFollowingPerformer field.
func (r *mutationResolver) RefreshFollowingPerformer(ctx context.Context, stashPerformerID string) (*model.FollowingPerformer, error) {
	if r.Following == nil {
		return nil, errors.New("following service is not configured")
	}

	item, err := r.Following.RefreshPerformer(ctx, stashPerformerID)
	if err != nil {
		return followingPerformerToModel(item), err
	}
	return followingPerformerToModel(item), nil
}

// RefreshFollowingNow is the resolver for the refreshFollowingNow field.
func (r *mutationResolver) RefreshFollowingNow(ctx context.Context) ([]*model.FollowingPerformer, error) {
	if r.Following == nil {
		return nil, errors.New("following service is not configured")
	}

	items, err := r.Following.RefreshAll(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.FollowingPerformer, 0, len(items))
	for _, item := range items {
		out = append(out, followingPerformerToModel(item))
	}
	return out, nil
}

// StashPerformers is the resolver for the stashPerformers field.
func (r *queryResolver) StashPerformers(ctx context.Context, search *string, page *int, pageSize *int) (*model.StashPerformerConnection, error) {
	if r.Following == nil {
		return stashPerformerPageToModel(StashPerformerPage{
			Items:       nil,
			Page:        1,
			PageSize:    normalizePageSize(pageSize),
			TotalCount:  0,
			TotalPages:  0,
			HasPrevPage: false,
			HasNextPage: false,
		}), nil
	}

	needle := ""
	if search != nil {
		needle = *search
	}

	items, err := r.Following.ListStashPerformers(ctx, needle)
	if err != nil {
		return nil, err
	}

	currentPage := normalizePage(page)
	currentPageSize := normalizePageSize(pageSize)
	totalCount := len(items)
	totalPages := 0
	if totalCount > 0 {
		totalPages = int(math.Ceil(float64(totalCount) / float64(currentPageSize)))
	}
	if totalPages > 0 && currentPage > totalPages {
		currentPage = totalPages
	}

	start := 0
	end := 0
	if totalCount > 0 {
		start = (currentPage - 1) * currentPageSize
		if start < 0 {
			start = 0
		}
		if start > totalCount {
			start = totalCount
		}
		end = start + currentPageSize
		if end > totalCount {
			end = totalCount
		}
	}

	return stashPerformerPageToModel(StashPerformerPage{
		Items:       items[start:end],
		Page:        currentPage,
		PageSize:    currentPageSize,
		TotalCount:  totalCount,
		TotalPages:  totalPages,
		HasPrevPage: currentPage > 1 && totalPages > 0,
		HasNextPage: currentPage < totalPages,
	}), nil
}

// FollowingPerformers is the resolver for the followingPerformers field.
func (r *queryResolver) FollowingPerformers(ctx context.Context) ([]*model.FollowingPerformer, error) {
	if r.Following == nil {
		return []*model.FollowingPerformer{}, nil
	}

	items, err := r.Following.ListFollowingPerformers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.FollowingPerformer, 0, len(items))
	for _, item := range items {
		out = append(out, followingPerformerToModel(item))
	}
	return out, nil
}
