package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context, limit *int, minLevel *model.LogLevel) ([]*model.LogEntry, error) {
	if r.LogReader == nil {
		return []*model.LogEntry{}, nil
	}

	size := 200
	if limit != nil && *limit > 0 {
		size = *limit
	}

	level := string(model.LogLevelInfo)
	if minLevel != nil {
		level = string(*minLevel)
	}

	entries := r.LogReader.Entries(size, level)
	out := make([]*model.LogEntry, 0, len(entries))
	for _, entry := range entries {
		out = append(out, &model.LogEntry{
			Sequence: entry.Sequence,
			Time:     formatTime(entry.Time),
			Level:    parseGraphQLLogLevel(entry.Level),
			Message:  entry.Message,
		})
	}
	return out, nil
}

// LogEvents is the resolver for the logEvents field.
func (r *subscriptionResolver) LogEvents(ctx context.Context) (<-chan *model.LogEvent, error) {
	out := make(chan *model.LogEvent, 1)
	if r.LogEventSource == nil {
		close(out)
		return out, nil
	}
	events := r.LogEventSource.Subscribe(ctx)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-events:
				if !ok {
					return
				}
				mapped := &model.LogEvent{
					Sequence: event.Sequence,
					Entry: &model.LogEntry{
						Sequence: event.Entry.Sequence,
						Time:     formatTime(event.Entry.Time),
						Level:    parseGraphQLLogLevel(event.Entry.Level),
						Message:  event.Entry.Message,
					},
				}
				select {
				case <-ctx.Done():
					return
				case out <- mapped:
				}
			}
		}
	}()
	return out, nil
}
