package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// PerformerSubscriptionEvents is the resolver for the performerSubscriptionEvents field.
func (r *subscriptionResolver) PerformerSubscriptionEvents(ctx context.Context) (<-chan *model.PerformerSubscriptionEvent, error) {
	out := make(chan *model.PerformerSubscriptionEvent, 1)
	if r.PerformerSubscriptionEventSource == nil {
		close(out)
		return out, nil
	}
	events := r.PerformerSubscriptionEventSource.Subscribe(ctx)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-events:
				if !ok {
					return
				}
				var state *model.SubscribedPerformer
				if event.State != nil {
					state = subscriptionPerformerToModel(*event.State)
				}
				mapped := &model.PerformerSubscriptionEvent{
					Sequence:    event.Sequence,
					Type:        model.PerformerSubscriptionEventType(event.Type),
					PerformerID: event.PerformerID,
					State:       state,
				}
				select {
				case <-ctx.Done():
					return
				case out <- mapped:
				}
			}
		}
	}()
	return out, nil
}
