package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"strings"

	"github.com/leothevan2444/moji/internal/graphqlapi/generated"
	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/tracker"
	"github.com/leothevan2444/moji/pkg/qbittorrent"
)

// QbittorrentAdd is the resolver for the qbittorrentAdd field.
func (r *mutationResolver) QbittorrentAdd(ctx context.Context, input model.QBittorrentAddInput) (bool, error) {
	if r.Torrent == nil {
		return false, errors.New("qBittorrent client is not configured")
	}

	torrentURL := strings.TrimSpace(input.URL)
	if torrentURL == "" {
		return false, errors.New("url is required")
	}

	options := qbittorrent.AddTorrentOptions{
		URLs: []string{torrentURL},
	}
	if input.SavePath != nil {
		options.SavePath = input.SavePath
	}
	if input.Category != nil {
		options.Category = input.Category
	}
	if input.Tags != nil {
		options.Tags = input.Tags
	}
	if input.Paused != nil {
		options.Paused = input.Paused
	}

	if err := r.Torrent.AddNewTorrent(ctx, options); err != nil {
		return false, err
	}
	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	return &model.Health{
		Ok:      true,
		Message: "ok",
	}, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	if r.AppVersion != "" {
		return r.AppVersion, nil
	}
	return "dev", nil
}

// JackettSearch is the resolver for the jackettSearch field.
func (r *queryResolver) JackettSearch(ctx context.Context, input model.JackettSearchInput) ([]*model.JackettSearchResult, error) {
	if r.Tracker == nil {
		return nil, errors.New("tracker is not configured")
	}

	query := strings.TrimSpace(input.Query)
	if query == "" {
		return nil, errors.New("query is required")
	}

	options := []tracker.SearchOption{
		tracker.WithTrackers(input.Trackers),
		tracker.WithCategories(input.Categories),
	}
	if input.Limit != nil {
		options = append(options, tracker.WithLimit(*input.Limit))
	}

	results, err := r.Tracker.Search(query, options...)
	if err != nil {
		return nil, err
	}

	out := make([]*model.JackettSearchResult, 0, len(results))
	for _, result := range results {
		out = append(out, jackettSearchResultToModel(result))
	}
	return out, nil
}

// QbittorrentTorrents is the resolver for the qbittorrentTorrents field.
func (r *queryResolver) QbittorrentTorrents(ctx context.Context, limit *int) ([]*model.QBTorrent, error) {
	if r.Torrent == nil {
		return nil, errors.New("qBittorrent client is not configured")
	}

	var options *qbittorrent.TorrentListOptions
	if limit != nil {
		options = &qbittorrent.TorrentListOptions{Limit: limit}
	}

	torrents, err := r.Torrent.GetTorrentList(ctx, options)
	if err != nil {
		return nil, err
	}

	out := make([]*model.QBTorrent, 0, len(torrents))
	for _, torrent := range torrents {
		out = append(out, qbTorrentToModel(torrent))
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
