package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"strings"

	"github.com/leothevan2444/moji/internal/downloader"
	"github.com/leothevan2444/moji/internal/graphqlapi/generated"
	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/stashsync"
	"github.com/leothevan2444/moji/internal/tracker"
	"github.com/leothevan2444/moji/pkg/qbittorrent"
)

// QbittorrentAdd is the resolver for the qbittorrentAdd field.
func (r *mutationResolver) QbittorrentAdd(ctx context.Context, input model.QBittorrentAddInput) (bool, error) {
	if _, err := r.AddTorrent(ctx, input); err != nil {
		return false, err
	}
	return true, nil
}

// AddTorrent is the resolver for the addTorrent field.
func (r *mutationResolver) AddTorrent(ctx context.Context, input model.QBittorrentAddInput) (*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}

	req := downloader.AddTorrentRequest{
		URL:    input.URL,
		Paused: input.Paused,
	}
	if input.SavePath != nil {
		req.SavePath = *input.SavePath
	}
	if input.Category != nil {
		req.Category = *input.Category
	}
	if input.Tags != nil {
		req.Tags = *input.Tags
	}

	task, err := r.Downloader.AddTorrentContext(ctx, req)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// DownloadMedia is the resolver for the downloadMedia field.
func (r *mutationResolver) DownloadMedia(ctx context.Context, input model.DownloadMediaInput) (*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}

	req := downloader.DownloadRequest{
		Query:      input.Query,
		Trackers:   input.Trackers,
		Categories: input.Categories,
		Paused:     input.Paused,
	}
	if input.Limit != nil {
		req.Limit = *input.Limit
	}
	if input.SavePath != nil {
		req.SavePath = *input.SavePath
	}
	if input.Category != nil {
		req.Category = *input.Category
	}
	if input.Tags != nil {
		req.Tags = *input.Tags
	}

	task, err := r.Downloader.DownloadMediaContext(ctx, req)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// SyncTaskProgress is the resolver for the syncTaskProgress field.
func (r *mutationResolver) SyncTaskProgress(ctx context.Context) ([]*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}

	tasks, err := r.Downloader.SyncProgress(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Task, 0, len(tasks))
	for _, task := range tasks {
		out = append(out, taskToModel(task))
	}
	return out, nil
}

// StashMetadataScan is the resolver for the stashMetadataScan field.
func (r *mutationResolver) StashMetadataScan(ctx context.Context, input model.StashMetadataScanInput) (string, error) {
	if r.Stash == nil {
		return "", errors.New("stash client is not configured")
	}

	return r.Stash.MetadataScan(ctx, stashsync.ScanRequest{
		Paths:                     input.Paths,
		Rescan:                    input.Rescan,
		ScanGenerateCovers:        input.ScanGenerateCovers,
		ScanGeneratePreviews:      input.ScanGeneratePreviews,
		ScanGenerateImagePreviews: input.ScanGenerateImagePreviews,
		ScanGenerateSprites:       input.ScanGenerateSprites,
		ScanGeneratePhashes:       input.ScanGeneratePhashes,
		ScanGenerateThumbnails:    input.ScanGenerateThumbnails,
		ScanGenerateClipPreviews:  input.ScanGenerateClipPreviews,
	})
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	return &model.Health{
		Ok:      true,
		Message: "ok",
	}, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	if r.AppVersion != "" {
		return r.AppVersion, nil
	}
	return "dev", nil
}

// JackettSearch is the resolver for the jackettSearch field.
func (r *queryResolver) JackettSearch(ctx context.Context, input model.JackettSearchInput) ([]*model.JackettSearchResult, error) {
	if r.Tracker == nil {
		return nil, errors.New("tracker is not configured")
	}

	query := strings.TrimSpace(input.Query)
	if query == "" {
		return nil, errors.New("query is required")
	}

	options := []tracker.SearchOption{
		tracker.WithTrackers(input.Trackers),
		tracker.WithCategories(input.Categories),
	}
	if input.Limit != nil {
		options = append(options, tracker.WithLimit(*input.Limit))
	}

	results, err := r.Tracker.Search(query, options...)
	if err != nil {
		return nil, err
	}

	out := make([]*model.JackettSearchResult, 0, len(results))
	for _, result := range results {
		out = append(out, jackettSearchResultToModel(result))
	}
	return out, nil
}

// QbittorrentTorrents is the resolver for the qbittorrentTorrents field.
func (r *queryResolver) QbittorrentTorrents(ctx context.Context, limit *int) ([]*model.QBTorrent, error) {
	if r.Torrent == nil {
		return nil, errors.New("qBittorrent client is not configured")
	}

	var options *qbittorrent.TorrentListOptions
	if limit != nil {
		options = &qbittorrent.TorrentListOptions{Limit: limit}
	}

	torrents, err := r.Torrent.GetTorrentList(ctx, options)
	if err != nil {
		return nil, err
	}

	out := make([]*model.QBTorrent, 0, len(torrents))
	for _, torrent := range torrents {
		out = append(out, qbTorrentToModel(torrent))
	}
	return out, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}

	task, err := r.Downloader.FindTask(ctx, id)
	if err != nil {
		return nil, err
	}
	return taskToModel(task), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}

	tasks, err := r.Downloader.ListTasks(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Task, 0, len(tasks))
	for _, task := range tasks {
		out = append(out, taskToModel(task))
	}
	return out, nil
}

// StashJob is the resolver for the stashJob field.
func (r *queryResolver) StashJob(ctx context.Context, id string) (*model.StashJob, error) {
	if r.Stash == nil {
		return nil, errors.New("stash client is not configured")
	}

	job, err := r.Stash.FindJob(ctx, id)
	if err != nil {
		return nil, err
	}

	return stashJobToModel(job), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
