package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"strings"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/subscription"
	"github.com/leothevan2444/moji/internal/tracker"
)

// QueueDiscoveredScene is the resolver for the queueDiscoveredScene field.
func (r *mutationResolver) QueueDiscoveredScene(ctx context.Context, input model.QueueDiscoveredSceneInput) (*model.Task, error) {
	if r.Subscription == nil {
		return nil, errors.New("subscription service is not configured")
	}
	task, err := r.Subscription.QueueDiscoveredScene(ctx, input.SceneID, input.StashBoxEndpoint)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// DiscoverScenes is the resolver for the discoverScenes field.
func (r *queryResolver) DiscoverScenes(ctx context.Context, input model.DiscoverScenesInput) (*model.DiscoverSceneConnection, error) {
	if r.Subscription == nil {
		return nil, errors.New("subscription service is not configured")
	}

	query := strings.TrimSpace(input.Query)
	if query == "" {
		return nil, errors.New("query is required")
	}
	limit := 50
	if input.Limit != nil {
		limit = *input.Limit
	}
	sortBy := mapDiscoverSortBy(input.SortBy)

	page, err := r.Subscription.SearchPreferredStashBoxScenes(ctx, query, limit, sortBy)
	if err != nil {
		return nil, err
	}
	return discoveredScenePageToModel(page), nil
}

// JackettSearch is the resolver for the jackettSearch field.
func (r *queryResolver) JackettSearch(ctx context.Context, input model.JackettSearchInput) ([]*model.JackettSearchResult, error) {
	if r.Tracker == nil {
		return nil, errors.New("tracker is not configured")
	}

	query := strings.TrimSpace(input.Query)
	if query == "" {
		return nil, errors.New("query is required")
	}

	options := []tracker.SearchOption{
		tracker.WithTrackers(input.Trackers),
		tracker.WithCategories(input.Categories),
	}
	if input.Limit != nil {
		options = append(options, tracker.WithLimit(*input.Limit))
	}

	results, err := r.Tracker.Search(query, options...)
	if err != nil {
		return nil, err
	}

	out := make([]*model.JackettSearchResult, 0, len(results))
	for _, result := range results {
		out = append(out, jackettSearchResultToModel(result))
	}
	sortJackettResults(out, input.SortBy)
	return out, nil
}

// JackettIndexers is the resolver for the jackettIndexers field. Returns an
// empty list when the active tracker is not a Jackett service or when Jackett
// itself is not configured — the frontend treats that as "未连接".
func (r *queryResolver) JackettIndexers(ctx context.Context) ([]*model.JackettIndexer, error) {
	if r.Tracker == nil {
		return []*model.JackettIndexer{}, nil
	}
	lister, ok := r.Tracker.(tracker.IndexerLister)
	if !ok {
		return []*model.JackettIndexer{}, nil
	}
	indexers, err := lister.ListIndexers()
	if err != nil {
		return []*model.JackettIndexer{}, nil
	}
	out := make([]*model.JackettIndexer, 0, len(indexers))
	for _, indexer := range indexers {
		out = append(out, jackettIndexerToModel(indexer))
	}
	return out, nil
}

// mapDiscoverSortBy translates the GraphQL enum into the subscription-domain
// enum so resolver code doesn't depend on gqlgen-generated types directly.
func mapDiscoverSortBy(value *model.DiscoverSortBy) subscription.DiscoverSort {
	if value == nil {
		return subscription.DiscoverSortRelevance
	}
	switch *value {
	case model.DiscoverSortByRelevance:
		return subscription.DiscoverSortRelevance
	case model.DiscoverSortByDateDesc:
		return subscription.DiscoverSortDateDesc
	case model.DiscoverSortByDateAsc:
		return subscription.DiscoverSortDateAsc
	case model.DiscoverSortByDurationDesc:
		return subscription.DiscoverSortDurationDesc
	case model.DiscoverSortByTitleAsc:
		return subscription.DiscoverSortTitleAsc
	default:
		return subscription.DiscoverSortRelevance
	}
}