package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"strings"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/tracker"
)

// JackettSearch is the resolver for the jackettSearch field.
func (r *queryResolver) JackettSearch(ctx context.Context, input model.JackettSearchInput) ([]*model.JackettSearchResult, error) {
	if r.Tracker == nil {
		return nil, errors.New("tracker is not configured")
	}

	query := strings.TrimSpace(input.Query)
	if query == "" {
		return nil, errors.New("query is required")
	}

	options := []tracker.SearchOption{
		tracker.WithTrackers(input.Trackers),
		tracker.WithCategories(input.Categories),
	}
	if input.Limit != nil {
		options = append(options, tracker.WithLimit(*input.Limit))
	}

	results, err := r.Tracker.Search(query, options...)
	if err != nil {
		return nil, err
	}

	out := make([]*model.JackettSearchResult, 0, len(results))
	for _, result := range results {
		out = append(out, jackettSearchResultToModel(result))
	}
	return out, nil
}
