package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// ServiceStatusEvents is the resolver for the serviceStatusEvents field.
func (r *subscriptionResolver) ServiceStatusEvents(ctx context.Context) (<-chan *model.ServiceStatusEvent, error) {
	out := make(chan *model.ServiceStatusEvent, 1)
	if r.ServiceStatusEventSource == nil {
		close(out)
		return out, nil
	}
	events := r.ServiceStatusEventSource.Subscribe(ctx)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-events:
				if !ok {
					return
				}
				services := make([]model.ExternalService, 0, len(event.Services))
				for _, service := range event.Services {
					services = append(services, model.ExternalService(service))
				}
				mapped := &model.ServiceStatusEvent{
					Sequence:   event.Sequence,
					Services:   services,
					ObservedAt: formatTime(event.ObservedAt),
				}
				select {
				case <-ctx.Done():
					return
				case out <- mapped:
				}
			}
		}
	}()
	return out, nil
}
