package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"strings"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// UpdateStashSettings is the resolver for the updateStashSettings field.
func (r *mutationResolver) UpdateStashSettings(ctx context.Context, input model.UpdateStashSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateStashSettings(UpdateStashSettingsInput{
		URL:                   input.URL,
		APIKey:                strings.TrimSpace(derefString(input.APIKey)),
		Mode:                  input.Mode,
		LibraryPath:           input.LibraryPath,
		QBittorrentPathPrefix: input.QbittorrentPathPrefix,
		StashPathPrefix:       input.StashPathPrefix,
		TransferAction:        input.TransferAction,
		TransferTargetPath:    input.TransferTargetPath,
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateJackettSettings is the resolver for the updateJackettSettings field.
func (r *mutationResolver) UpdateJackettSettings(ctx context.Context, input model.UpdateJackettSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateJackettSettings(UpdateJackettSettingsInput{
		URL:    input.URL,
		APIKey: strings.TrimSpace(derefString(input.APIKey)),
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateQBittorrentSettings is the resolver for the updateQBittorrentSettings field.
func (r *mutationResolver) UpdateQBittorrentSettings(ctx context.Context, input model.UpdateQBittorrentSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateQBittorrentSettings(UpdateQBittorrentSettingsInput{
		URL:             input.URL,
		Username:        input.Username,
		Password:        strings.TrimSpace(derefString(input.Password)),
		DefaultSavePath: input.DefaultSavePath,
		Category:        input.Category,
		Tags:            input.Tags,
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateSubscriptionSettings is the resolver for the updateSubscriptionSettings field.
func (r *mutationResolver) UpdateSubscriptionSettings(ctx context.Context, input model.UpdateSubscriptionSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateSubscriptionSettings(UpdateSubscriptionSettingsInput{
		Store:               input.Store,
		DBPath:              input.DbPath,
		PollIntervalSeconds: input.PollIntervalSeconds,
		StashBoxEndpoints:   append([]string(nil), input.StashBoxEndpoints...),
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// RefreshSubscriptionStashBoxes is the resolver for the
// refreshSubscriptionStashBoxes field. It re-queries the configured Stash
// server for the Stash-Box list so the UI can pick up additions/removals
// without restarting Moji.
func (r *mutationResolver) RefreshSubscriptionStashBoxes(ctx context.Context) (*model.Settings, error) {
	if r.Subscription == nil {
		return nil, errors.New("subscription service is not configured")
	}
	if err := r.Subscription.RefreshStashBoxes(ctx); err != nil {
		return nil, err
	}
	if r.SettingsEditor != nil {
		return settingsSnapshotToModel(r.SettingsEditor.Snapshot(), r.AppVersion), nil
	}
	return settingsSnapshotToModel(r.RuntimeSettings, r.AppVersion), nil
}

// UpdateLoggingSettings is the resolver for the updateLoggingSettings field.
func (r *mutationResolver) UpdateLoggingSettings(ctx context.Context, input model.UpdateLoggingSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateLoggingSettings(UpdateLoggingSettingsInput{
		Level:            input.Level,
		FilePath:         input.FilePath,
		MaxEntries:       input.MaxEntries,
		MaxFileSizeBytes: int64(input.MaxFileSizeBytes),
		MaxFileBackups:   input.MaxFileBackups,
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*model.Settings, error) {
	if r.SettingsEditor != nil {
		return settingsSnapshotToModel(r.SettingsEditor.Snapshot(), r.AppVersion), nil
	}

	return settingsSnapshotToModel(r.RuntimeSettings, r.AppVersion), nil
}
