package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"strings"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/stats"
)

// UpdateStashSettings is the resolver for the updateStashSettings field.
func (r *mutationResolver) UpdateStashSettings(ctx context.Context, input model.UpdateStashSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateStashSettings(UpdateStashSettingsInput{
		URL:    input.URL,
		APIKey: strings.TrimSpace(derefString(input.APIKey)),
	})
	if err != nil {
		return nil, err
	}
	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateIngestSettings is the resolver for the updateIngestSettings field.
func (r *mutationResolver) UpdateIngestSettings(ctx context.Context, input model.UpdateIngestSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateIngestSettings(UpdateIngestSettingsInput{
		DeliveryMode: input.DeliveryMode,
		Downloads: DownloadsIngestSettingsSnapshot{
			QBRoot:   input.Downloads.QbRoot,
			MojiRoot: input.Downloads.MojiRoot,
		},
		Library: LibraryIngestSettingsSnapshot{
			MojiRoot:  input.Library.MojiRoot,
			StashRoot: input.Library.StashRoot,
		},
		Transfer: TransferIngestSettingsSnapshot{
			Action: input.Transfer.Action,
		},
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateJackettSettings is the resolver for the updateJackettSettings field.
func (r *mutationResolver) UpdateJackettSettings(ctx context.Context, input model.UpdateJackettSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateJackettSettings(UpdateJackettSettingsInput{
		URL:      input.URL,
		APIKey:   strings.TrimSpace(derefString(input.APIKey)),
		Password: strings.TrimSpace(input.Password),
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateQBittorrentSettings is the resolver for the updateQBittorrentSettings field.
func (r *mutationResolver) UpdateQBittorrentSettings(ctx context.Context, input model.UpdateQBittorrentSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateQBittorrentSettings(UpdateQBittorrentSettingsInput{
		URL:             input.URL,
		Username:        input.Username,
		Password:        strings.TrimSpace(derefString(input.Password)),
		DefaultSavePath: input.DefaultSavePath,
		Category:        input.Category,
		Tags:            input.Tags,
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateAutomationSettings is the resolver for the updateAutomationSettings field.
func (r *mutationResolver) UpdateAutomationSettings(ctx context.Context, input model.UpdateAutomationSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	snapshot, err := r.SettingsEditor.UpdateAutomationSettings(UpdateAutomationSettingsInput{
		TaskProgressSyncIntervalSeconds: input.TaskProgressSyncIntervalSeconds,
		SubscriptionPollIntervalHours:   input.SubscriptionPollIntervalHours,
		StashBoxEndpoints:               append([]string(nil), input.StashBoxEndpoints...),
		SubscriptionReleasePolicy: SubscriptionReleasePolicySnapshot{
			SoloBehavior:           string(input.SubscriptionReleasePolicy.SoloBehavior),
			GroupBehavior:          string(input.SubscriptionReleasePolicy.GroupBehavior),
			CompilationBehavior:    string(input.SubscriptionReleasePolicy.CompilationBehavior),
			MaxGroupPerformerCount: input.SubscriptionReleasePolicy.MaxGroupPerformerCount,
			ReleaseDateRange:       string(input.SubscriptionReleasePolicy.ReleaseDateRange),
		},
		TorrentSelection: torrentSelectionSettingsFromModel(input.TorrentSelection),
	})
	if err != nil {
		return nil, err
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// UpdateSystemSettings is the resolver for the updateSystemSettings field.
func (r *mutationResolver) UpdateSystemSettings(ctx context.Context, input model.UpdateSystemSettingsInput) (*model.Settings, error) {
	_ = ctx
	if r.SettingsEditor == nil {
		return nil, errors.New("settings editor is not configured")
	}

	cacheSettings := ImageCacheSettingsSnapshot{Enabled: true, MaxSizeMB: 1024, RetentionDays: 30}
	if current := r.SettingsEditor.Snapshot(); current != nil {
		cacheSettings = current.System.ImageCache
	}
	if input.ImageCache != nil {
		cacheSettings = ImageCacheSettingsSnapshot{Enabled: input.ImageCache.Enabled, MaxSizeMB: input.ImageCache.MaxSizeMb, RetentionDays: input.ImageCache.RetentionDays}
	}
	snapshot, err := r.SettingsEditor.UpdateSystemSettings(UpdateSystemSettingsInput{TaskDeletePolicy: string(input.TaskDeletePolicy), ImageCache: cacheSettings})
	if err != nil {
		return nil, err
	}
	if r.ImageCache != nil {
		_ = r.ImageCache.Cleanup(ctx)
	}

	return settingsSnapshotToModel(snapshot, r.AppVersion), nil
}

// RefreshSubscriptionStashBoxes is the resolver for the
// refreshSubscriptionStashBoxes field. It re-queries the configured Stash
// server for the Stash-Box list so the UI can pick up additions/removals
// without restarting Moji.
func (r *mutationResolver) RefreshSubscriptionStashBoxes(ctx context.Context) (*model.Settings, error) {
	if r.Subscription == nil {
		return nil, errors.New("subscription service is not configured")
	}
	if err := r.Subscription.RefreshStashBoxes(ctx); err != nil {
		return nil, err
	}
	if r.SettingsEditor != nil {
		return settingsSnapshotToModel(r.SettingsEditor.Snapshot(), r.AppVersion), nil
	}
	return settingsSnapshotToModel(r.RuntimeSettings, r.AppVersion), nil
}

// ClearImageCache is the resolver for the clearImageCache field.
func (r *mutationResolver) ClearImageCache(ctx context.Context) (*model.ImageCacheStatus, error) {
	if r.ImageCache == nil {
		return nil, errors.New("image cache is not configured")
	}
	status, err := r.ImageCache.Clear(ctx)
	if err != nil {
		return nil, err
	}
	return imageCacheStatusToModel(status), nil
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*model.Settings, error) {
	if r.SettingsEditor != nil {
		return settingsSnapshotToModel(r.SettingsEditor.Snapshot(), r.AppVersion), nil
	}

	return settingsSnapshotToModel(r.RuntimeSettings, r.AppVersion), nil
}

// SettingsStatus is the resolver for the settingsStatus field.
func (r *queryResolver) SettingsStatus(ctx context.Context) (*model.SettingsStatus, error) {
	var snap *SettingsStatusSnapshot
	if r.SettingsEditor != nil {
		snap = r.SettingsEditor.StatusSnapshot()
	} else {
		snap = r.RuntimeStatus
	}

	var statsSnap *stats.Snapshot
	if r.Stats != nil {
		s := r.Stats.SnapshotView()
		statsSnap = &s
	}

	out := SettingsStatusWithStats(snap, statsSnap)
	if r.ImageCache != nil {
		status, err := r.ImageCache.Status(ctx)
		if err == nil {
			out.ImageCache = imageCacheStatusToModel(status)
		}
	}
	if out.ImageCache == nil {
		out.ImageCache = &model.ImageCacheStatus{}
	}
	return out, nil
}
