package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/stashsync"
)

// StashMetadataScan is the resolver for the stashMetadataScan field.
func (r *mutationResolver) StashMetadataScan(ctx context.Context, input model.StashMetadataScanInput) (string, error) {
	if r.Stash == nil {
		return "", errors.New("stash client is not configured")
	}

	return r.Stash.MetadataScan(ctx, stashsync.ScanRequest{
		Paths:                     input.Paths,
		Rescan:                    input.Rescan,
		ScanGenerateCovers:        input.ScanGenerateCovers,
		ScanGeneratePreviews:      input.ScanGeneratePreviews,
		ScanGenerateImagePreviews: input.ScanGenerateImagePreviews,
		ScanGenerateSprites:       input.ScanGenerateSprites,
		ScanGeneratePhashes:       input.ScanGeneratePhashes,
		ScanGenerateThumbnails:    input.ScanGenerateThumbnails,
		ScanGenerateClipPreviews:  input.ScanGenerateClipPreviews,
	})
}

// StashJob is the resolver for the stashJob field.
func (r *queryResolver) StashJob(ctx context.Context, id string) (*model.StashJob, error) {
	if r.Stash == nil {
		return nil, errors.New("stash client is not configured")
	}

	job, err := r.Stash.FindJob(ctx, id)
	if err != nil {
		return nil, err
	}

	return stashJobToModel(job), nil
}
