package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/leothevan2444/moji/internal/downloader"
	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// DashboardStats is the resolver for the dashboardStats field.
func (r *queryResolver) DashboardStats(ctx context.Context) (*model.DashboardStats, error) {
	if r.Downloader == nil {
		return &model.DashboardStats{}, nil
	}

	tasks, err := r.Downloader.ListTasks(ctx)
	if err != nil {
		return nil, err
	}

	stats := &model.DashboardStats{
		Total: len(tasks),
	}
	for _, task := range tasks {
		if task == nil {
			continue
		}

		if task.Stage != downloader.TaskStageCompleted {
			stats.Active++
		}
		if task.Stage == downloader.TaskStageCompleted {
			stats.Completed++
		}
		if task.Stage == downloader.TaskStageDownloading && task.StageStatus == downloader.TaskStageStatusRunning {
			stats.Downloading++
		}
		if task.Stage == downloader.TaskStagePendingIngest || task.Stage == downloader.TaskStageTransferring || task.Stage == downloader.TaskStageScanning {
			stats.PendingScans++
		}
		if task.StageStatus == downloader.TaskStageStatusBlocked {
			stats.Failed++
		}
	}

	return stats, nil
}
