package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"strings"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// DashboardStats is the resolver for the dashboardStats field.
func (r *queryResolver) DashboardStats(ctx context.Context) (*model.DashboardStats, error) {
	if r.Downloader == nil {
		return &model.DashboardStats{}, nil
	}

	tasks, err := r.Downloader.ListTasks(ctx)
	if err != nil {
		return nil, err
	}

	stats := &model.DashboardStats{
		Total: len(tasks),
	}
	for _, task := range tasks {
		if task == nil {
			continue
		}

		status := strings.TrimSpace(strings.ToLower(string(task.Status)))
		scanStatus := strings.TrimSpace(strings.ToLower(task.StashScanStatus))

		if !isTaskTerminalStatus(status) {
			stats.Active++
		}
		if status == "completed" {
			stats.Completed++
		}
		if isDownloadingStatus(status) {
			stats.Downloading++
		}
		if isPendingScanStatus(scanStatus) {
			stats.PendingScans++
		}
		if status == "failed" || task.StashScanError != "" {
			stats.Failed++
		}
	}

	return stats, nil
}
