package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// SubscribePerformer is the resolver for the subscribePerformer field.
func (r *mutationResolver) SubscribePerformer(ctx context.Context, stashPerformerID string) (*model.SubscribedPerformer, error) {
	if r.Subscription == nil {
		return nil, errors.New("subscription service is not configured")
	}

	item, err := r.Subscription.SubscribePerformer(ctx, stashPerformerID)
	if err != nil {
		return nil, err
	}
	return subscriptionPerformerToModel(item), nil
}

// UnsubscribePerformer is the resolver for the unsubscribePerformer field.
func (r *mutationResolver) UnsubscribePerformer(ctx context.Context, stashPerformerID string) (bool, error) {
	if r.Subscription == nil {
		return false, errors.New("subscription service is not configured")
	}

	if err := r.Subscription.UnsubscribePerformer(ctx, stashPerformerID); err != nil {
		return false, err
	}
	return true, nil
}

// RefreshSubscribedPerformer is the resolver for the refreshSubscribedPerformer field.
func (r *mutationResolver) RefreshSubscribedPerformer(ctx context.Context, stashPerformerID string) (*model.SubscribedPerformer, error) {
	if r.Subscription == nil {
		return nil, errors.New("subscription service is not configured")
	}

	item, err := r.Subscription.RefreshSubscribedPerformer(ctx, stashPerformerID)
	if err != nil {
		return subscriptionPerformerToModel(item), err
	}
	return subscriptionPerformerToModel(item), nil
}

// RefreshSubscriptionsNow is the resolver for the refreshSubscriptionsNow field.
func (r *mutationResolver) RefreshSubscriptionsNow(ctx context.Context) ([]*model.SubscribedPerformer, error) {
	panic(fmt.Errorf("not implemented: RefreshSubscriptionsNow - refreshSubscriptionsNow"))
}

// StashPerformers is the resolver for the stashPerformers field.
func (r *queryResolver) StashPerformers(ctx context.Context, search *string, page *int, pageSize *int) (*model.StashPerformerConnection, error) {
	if r.Subscription == nil {
		return stashPerformerPageToModel(StashPerformerPage{
			Items:       nil,
			Page:        1,
			PageSize:    normalizePageSize(pageSize),
			TotalCount:  0,
			TotalPages:  0,
			HasPrevPage: false,
			HasNextPage: false,
		}), nil
	}

	needle := ""
	if search != nil {
		needle = *search
	}

	items, err := r.Subscription.ListStashPerformers(ctx, needle)
	if err != nil {
		return nil, err
	}

	currentPage := normalizePage(page)
	currentPageSize := normalizePageSize(pageSize)
	totalCount := len(items)
	totalPages := 0
	if totalCount > 0 {
		totalPages = int(math.Ceil(float64(totalCount) / float64(currentPageSize)))
	}
	if totalPages > 0 && currentPage > totalPages {
		currentPage = totalPages
	}

	start := 0
	end := 0
	if totalCount > 0 {
		start = (currentPage - 1) * currentPageSize
		if start < 0 {
			start = 0
		}
		if start > totalCount {
			start = totalCount
		}
		end = start + currentPageSize
		if end > totalCount {
			end = totalCount
		}
	}

	return stashPerformerPageToModel(StashPerformerPage{
		Items:       items[start:end],
		Page:        currentPage,
		PageSize:    currentPageSize,
		TotalCount:  totalCount,
		TotalPages:  totalPages,
		HasPrevPage: currentPage > 1 && totalPages > 0,
		HasNextPage: currentPage < totalPages,
	}), nil
}

// SubscribedPerformers is the resolver for the subscribedPerformers field.
func (r *queryResolver) SubscribedPerformers(ctx context.Context) ([]*model.SubscribedPerformer, error) {
	if r.Subscription == nil {
		return []*model.SubscribedPerformer{}, nil
	}

	items, err := r.Subscription.ListSubscribedPerformers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.SubscribedPerformer, 0, len(items))
	for _, item := range items {
		out = append(out, subscriptionPerformerToModel(item))
	}
	return out, nil
}
