package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"math"

	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/performer"
)

// SubscribePerformer is the resolver for the subscribePerformer field.
func (r *mutationResolver) SubscribePerformer(ctx context.Context, stashPerformerID string) (*model.SubscribedPerformer, error) {
	if r.PerformerSubscription == nil {
		return nil, errors.New("subscription service is not configured")
	}

	item, err := r.PerformerSubscription.SubscribePerformer(ctx, stashPerformerID)
	if err != nil {
		return nil, err
	}
	return subscriptionPerformerToModel(item), nil
}

// UnsubscribePerformer is the resolver for the unsubscribePerformer field.
func (r *mutationResolver) UnsubscribePerformer(ctx context.Context, stashPerformerID string) (bool, error) {
	if r.PerformerSubscription == nil {
		return false, errors.New("subscription service is not configured")
	}

	if err := r.PerformerSubscription.UnsubscribePerformer(ctx, stashPerformerID); err != nil {
		return false, err
	}
	return true, nil
}

// RefreshSubscribedPerformer is the resolver for the refreshSubscribedPerformer field.
func (r *mutationResolver) RefreshSubscribedPerformer(ctx context.Context, stashPerformerID string) (*model.SubscribedPerformer, error) {
	if r.PerformerSubscription == nil {
		return nil, errors.New("subscription service is not configured")
	}

	item, err := r.PerformerSubscription.RefreshSubscribedPerformer(ctx, stashPerformerID)
	if err != nil {
		return subscriptionPerformerToModel(item), err
	}
	return subscriptionPerformerToModel(item), nil
}

// RefreshSubscriptionsNow is the resolver for the refreshSubscriptionsNow field.
func (r *mutationResolver) RefreshSubscriptionsNow(ctx context.Context) ([]*model.SubscribedPerformer, error) {
	if r.PerformerSubscription == nil {
		return []*model.SubscribedPerformer{}, nil
	}

	items, err := r.PerformerSubscription.RefreshAll(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.SubscribedPerformer, 0, len(items))
	for _, item := range items {
		out = append(out, subscriptionPerformerToModel(item))
	}
	return out, nil
}

// QueuePerformerScenes is the resolver for the queuePerformerScenes field.
func (r *mutationResolver) QueuePerformerScenes(ctx context.Context, input model.QueuePerformerScenesInput) (*model.QueuePerformerScenesPayload, error) {
	if r.Performer == nil {
		return nil, errors.New("performer service is not configured")
	}

	selections := make([]performer.QueueSceneSelection, 0, len(input.Scenes))
	for _, scene := range input.Scenes {
		selections = append(selections, performer.QueueSceneSelection{
			Key:              scene.Key,
			SourceSceneID:    scene.SourceSceneID,
			StashBoxSceneID:  derefString(scene.StashBoxSceneID),
			StashBoxEndpoint: derefString(scene.StashBoxEndpoint),
			Code:             derefString(scene.Code),
			Title:            derefString(scene.Title),
			InLibrary:        scene.InLibrary,
		})
	}

	result, err := r.Performer.QueuePerformerScenes(ctx, input.PerformerID, selections)
	if err != nil {
		return nil, err
	}
	return queuePerformerScenesResultToModel(result), nil
}

// StashPerformers is the resolver for the stashPerformers field.
func (r *queryResolver) StashPerformers(ctx context.Context, search *string, page *int, pageSize *int) (*model.StashPerformerConnection, error) {
	if r.Performer == nil {
		return stashPerformerPageToModel(StashPerformerPage{
			Items:       nil,
			Page:        1,
			PageSize:    normalizePageSize(pageSize),
			TotalCount:  0,
			TotalPages:  0,
			HasPrevPage: false,
			HasNextPage: false,
		}), nil
	}

	needle := ""
	if search != nil {
		needle = *search
	}

	items, err := r.Performer.List(ctx, needle)
	if err != nil {
		return nil, err
	}

	currentPage := normalizePage(page)
	currentPageSize := normalizePageSize(pageSize)
	totalCount := len(items)
	totalPages := 0
	if totalCount > 0 {
		totalPages = int(math.Ceil(float64(totalCount) / float64(currentPageSize)))
	}
	if totalPages > 0 && currentPage > totalPages {
		currentPage = totalPages
	}

	start := 0
	end := 0
	if totalCount > 0 {
		start = (currentPage - 1) * currentPageSize
		if start < 0 {
			start = 0
		}
		if start > totalCount {
			start = totalCount
		}
		end = start + currentPageSize
		if end > totalCount {
			end = totalCount
		}
	}

	return stashPerformerPageToModel(StashPerformerPage{
		Items:       items[start:end],
		Page:        currentPage,
		PageSize:    currentPageSize,
		TotalCount:  totalCount,
		TotalPages:  totalPages,
		HasPrevPage: currentPage > 1 && totalPages > 0,
		HasNextPage: currentPage < totalPages,
	}), nil
}

// StashPerformerDetail is the resolver for the stashPerformerDetail field.
func (r *queryResolver) StashPerformerDetail(ctx context.Context, id string) (*model.StashPerformerDetail, error) {
	if r.Performer == nil {
		return nil, errors.New("performer service is not configured")
	}

	item, err := r.Performer.GetPerformerDetail(ctx, id)
	if err != nil {
		return nil, err
	}
	return stashPerformerDetailToModel(item), nil
}

// StashPerformerScenes is the resolver for the stashPerformerScenes field.
func (r *queryResolver) StashPerformerScenes(ctx context.Context, id string, input model.StashPerformerScenesInput) (*model.StashPerformerSceneConnection, error) {
	if r.Performer == nil {
		return performerScenePageToModel(performer.ScenePage{
			Page:     normalizePage(input.Page),
			PageSize: normalizePageSize(input.PageSize),
		}), nil
	}

	query := performer.SceneQuery{
		Search:   derefString(input.Search),
		Page:     normalizePage(input.Page),
		PageSize: normalizePageSize(input.PageSize),
	}
	if input.Source != nil {
		query.Source = performer.SceneSourceFilter(*input.Source)
	}
	if input.InLibrary != nil {
		query.InLibrary = performer.LibraryFilter(*input.InLibrary)
	}

	page, err := r.Performer.ListPerformerScenes(ctx, id, query)
	if err != nil {
		return nil, err
	}
	return performerScenePageToModel(page), nil
}

// SubscribedPerformers is the resolver for the subscribedPerformers field.
func (r *queryResolver) SubscribedPerformers(ctx context.Context) ([]*model.SubscribedPerformer, error) {
	if r.PerformerSubscription == nil {
		return []*model.SubscribedPerformer{}, nil
	}

	items, err := r.PerformerSubscription.ListSubscribedPerformers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.SubscribedPerformer, 0, len(items))
	for _, item := range items {
		out = append(out, subscriptionPerformerToModel(item))
	}
	return out, nil
}
