package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/leothevan2444/moji/internal/graphqlapi/generated"
	"github.com/leothevan2444/moji/internal/graphqlapi/model"
)

// TaskEvents is the resolver for the taskEvents field.
func (r *subscriptionResolver) TaskEvents(ctx context.Context) (<-chan *model.TaskEvent, error) {
	out := make(chan *model.TaskEvent, 1)
	if r.TaskEventSource == nil {
		close(out)
		return out, nil
	}
	events := r.TaskEventSource.Subscribe(ctx)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-events:
				if !ok {
					return
				}
				mapped := taskEventToModel(event)
				select {
				case <-ctx.Done():
					return
				case out <- mapped:
				}
			}
		}
	}()
	return out, nil
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
