package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"

	"github.com/leothevan2444/moji/internal/graphqlapi/generated"
	"github.com/leothevan2444/moji/internal/graphqlapi/model"
	"github.com/leothevan2444/moji/internal/taskflow"
	"github.com/leothevan2444/moji/pkg/qbittorrent"
)

// QbittorrentAdd is the resolver for the qbittorrentAdd field.
func (r *mutationResolver) QbittorrentAdd(ctx context.Context, input model.QBittorrentAddInput) (bool, error) {
	if _, err := r.AddTorrent(ctx, input); err != nil {
		return false, err
	}
	return true, nil
}

// AddTorrent is the resolver for the addTorrent field.
func (r *mutationResolver) AddTorrent(ctx context.Context, input model.QBittorrentAddInput) (*model.Task, error) {
	if r.TaskFlow == nil {
		return nil, errors.New("downloader is not configured")
	}

	req := taskflow.CreateFromManualTorrentInput{
		URL:    input.URL,
		Paused: input.Paused,
	}
	if input.SavePath != nil {
		req.SavePath = *input.SavePath
	}
	if input.Category != nil {
		req.Category = *input.Category
	}
	if input.Tags != nil {
		req.Tags = *input.Tags
	}

	task, err := r.TaskFlow.CreateFromManualTorrent(ctx, req)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// DownloadMedia is the resolver for the downloadMedia field.
func (r *mutationResolver) DownloadMedia(ctx context.Context, input model.DownloadMediaInput) (*model.Task, error) {
	if r.TaskFlow == nil {
		return nil, errors.New("downloader is not configured")
	}

	req := taskflow.CreateFromSearchCodeInput{
		Code:       input.Code,
		Trackers:   input.Trackers,
		Categories: input.Categories,
		Paused:     input.Paused,
	}
	if input.Limit != nil {
		req.Limit = *input.Limit
	}
	if input.SavePath != nil {
		req.SavePath = *input.SavePath
	}
	if input.Category != nil {
		req.Category = *input.Category
	}
	if input.Tags != nil {
		req.Tags = *input.Tags
	}

	task, err := r.TaskFlow.CreateFromSearchCode(ctx, req)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// SyncTaskProgress is the resolver for the syncTaskProgress field.
func (r *mutationResolver) SyncTaskProgress(ctx context.Context) ([]*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}

	tasks, err := r.Downloader.SyncProgress(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Task, 0, len(tasks))
	for _, task := range tasks {
		out = append(out, taskToModel(task))
	}
	return out, nil
}

// TriggerTaskStashScan is the resolver for the triggerTaskStashScan field.
func (r *mutationResolver) TriggerTaskStashScan(ctx context.Context, id string) (*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}
	if r.Stash == nil {
		return nil, errors.New("stash client is not configured")
	}

	task, err := r.Downloader.TriggerTaskStashScan(ctx, id, r.Stash)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// TriggerStashScans is the resolver for the triggerStashScans field.
func (r *mutationResolver) TriggerStashScans(ctx context.Context) ([]*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}
	if r.Stash == nil {
		return nil, errors.New("stash client is not configured")
	}

	tasks, err := r.Downloader.TriggerStashScans(ctx, r.Stash)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Task, 0, len(tasks))
	for _, task := range tasks {
		out = append(out, taskToModel(task))
	}
	return out, nil
}

// RetryTask is the resolver for the retryTask field.
func (r *mutationResolver) RetryTask(ctx context.Context, id string) (*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}
	task, err := r.Downloader.RetryTask(ctx, id, r.Stash)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (*model.Task, error) {
	if r.Downloader == nil {
		return nil, errors.New("downloader is not configured")
	}

	task, err := r.Downloader.DeleteTask(ctx, id)
	if task != nil {
		return taskToModel(task), err
	}
	return nil, err
}

// QbittorrentTorrents is the resolver for the qbittorrentTorrents field.
func (r *queryResolver) QbittorrentTorrents(ctx context.Context, limit *int) ([]*model.QBTorrent, error) {
	if r.Torrent == nil {
		return nil, errors.New("qBittorrent client is not configured")
	}

	var options *qbittorrent.TorrentListOptions
	if limit != nil {
		options = &qbittorrent.TorrentListOptions{Limit: limit}
	}

	torrents, err := r.Torrent.GetTorrentList(ctx, options)
	if err != nil {
		return nil, err
	}

	out := make([]*model.QBTorrent, 0, len(torrents))
	for _, torrent := range torrents {
		out = append(out, qbTorrentToModel(torrent))
	}
	return out, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	if r.Downloader == nil {
		return nil, nil
	}

	task, err := r.Downloader.FindTask(ctx, id)
	if err != nil {
		return nil, err
	}
	return taskToModel(task), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	if r.Downloader == nil {
		return []*model.Task{}, nil
	}

	tasks, err := r.Downloader.ListTasks(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Task, 0, len(tasks))
	for _, task := range tasks {
		out = append(out, taskToModel(task))
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
