// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DashboardStats struct {
	Total        int `json:"total"`
	Active       int `json:"active"`
	Completed    int `json:"completed"`
	Downloading  int `json:"downloading"`
	PendingScans int `json:"pendingScans"`
	Failed       int `json:"failed"`
}

type DownloadCandidate struct {
	Title     string `json:"title"`
	Tracker   string `json:"tracker"`
	InfoHash  string `json:"infoHash"`
	Link      string `json:"link"`
	MagnetURI string `json:"magnetUri"`
	Size      int64  `json:"size"`
	Seeders   int    `json:"seeders"`
	Peers     int    `json:"peers"`
}

type DownloadMediaInput struct {
	Query      string   `json:"query"`
	Trackers   []string `json:"trackers,omitempty"`
	Categories []int    `json:"categories,omitempty"`
	Limit      *int     `json:"limit,omitempty"`
	SavePath   *string  `json:"savePath,omitempty"`
	Category   *string  `json:"category,omitempty"`
	Tags       *string  `json:"tags,omitempty"`
	Paused     *bool    `json:"paused,omitempty"`
}

type FollowingPerformer struct {
	Performer             *StashPerformer     `json:"performer"`
	LastCheckedAt         *string             `json:"lastCheckedAt,omitempty"`
	LastError             *string             `json:"lastError,omitempty"`
	PendingReleaseCount   int                 `json:"pendingReleaseCount"`
	ProcessedReleaseCount int                 `json:"processedReleaseCount"`
	RecentReleases        []*FollowingRelease `json:"recentReleases"`
}

type FollowingRelease struct {
	Key    string  `json:"key"`
	Source string  `json:"source"`
	Title  string  `json:"title"`
	Code   *string `json:"code,omitempty"`
	Date   *string `json:"date,omitempty"`
	URL    *string `json:"url,omitempty"`
	Query  string  `json:"query"`
	TaskID *string `json:"taskID,omitempty"`
	SeenAt string  `json:"seenAt"`
}

// Basic service health
type Health struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

type JackettSearchInput struct {
	Query      string   `json:"query"`
	Trackers   []string `json:"trackers,omitempty"`
	Categories []int    `json:"categories,omitempty"`
	Limit      *int     `json:"limit,omitempty"`
}

type JackettSearchResult struct {
	Title        string `json:"title"`
	Size         int64  `json:"size"`
	Seeders      int    `json:"seeders"`
	Peers        int    `json:"peers"`
	Tracker      string `json:"tracker"`
	TrackerID    string `json:"trackerId"`
	CategoryDesc string `json:"categoryDesc"`
	PublishDate  string `json:"publishDate"`
	Details      string `json:"details"`
	Link         string `json:"link"`
	MagnetURI    string `json:"magnetUri"`
}

type JackettSettings struct {
	Configured       bool   `json:"configured"`
	Enabled          bool   `json:"enabled"`
	URL              string `json:"url"`
	APIKeyConfigured bool   `json:"apiKeyConfigured"`
}

type Mutation struct {
}

type QBTorrent struct {
	Hash     string  `json:"hash"`
	Name     string  `json:"name"`
	Progress float64 `json:"progress"`
	State    string  `json:"state"`
	Dlspeed  int64   `json:"dlspeed"`
	Upspeed  int64   `json:"upspeed"`
	Size     int64   `json:"size"`
	Eta      int64   `json:"eta"`
	Category string  `json:"category"`
	Tags     string  `json:"tags"`
	AddedOn  int64   `json:"addedOn"`
}

type QBittorrentAddInput struct {
	URL      string  `json:"url"`
	SavePath *string `json:"savePath,omitempty"`
	Category *string `json:"category,omitempty"`
	Tags     *string `json:"tags,omitempty"`
	Paused   *bool   `json:"paused,omitempty"`
}

type QBittorrentSettings struct {
	Configured         bool   `json:"configured"`
	Enabled            bool   `json:"enabled"`
	URL                string `json:"url"`
	Username           string `json:"username"`
	UsernameConfigured bool   `json:"usernameConfigured"`
	PasswordConfigured bool   `json:"passwordConfigured"`
	DefaultSavePath    string `json:"defaultSavePath"`
	Category           string `json:"category"`
	Tags               string `json:"tags"`
}

type Query struct {
}

type Settings struct {
	Stash       *StashSettings       `json:"stash"`
	Jackett     *JackettSettings     `json:"jackett"`
	Qbittorrent *QBittorrentSettings `json:"qbittorrent"`
	Tasks       *TaskSettings        `json:"tasks"`
	System      *SystemSettings      `json:"system"`
}

type StashJob struct {
	ID          string   `json:"id"`
	Status      string   `json:"status"`
	Description string   `json:"description"`
	Progress    *float64 `json:"progress,omitempty"`
	StartTime   *string  `json:"startTime,omitempty"`
	EndTime     *string  `json:"endTime,omitempty"`
	AddTime     string   `json:"addTime"`
	Error       *string  `json:"error,omitempty"`
	SubTasks    []string `json:"subTasks,omitempty"`
}

type StashMetadataScanInput struct {
	Paths                     []string `json:"paths,omitempty"`
	Rescan                    *bool    `json:"rescan,omitempty"`
	ScanGenerateCovers        *bool    `json:"scanGenerateCovers,omitempty"`
	ScanGeneratePreviews      *bool    `json:"scanGeneratePreviews,omitempty"`
	ScanGenerateImagePreviews *bool    `json:"scanGenerateImagePreviews,omitempty"`
	ScanGenerateSprites       *bool    `json:"scanGenerateSprites,omitempty"`
	ScanGeneratePhashes       *bool    `json:"scanGeneratePhashes,omitempty"`
	ScanGenerateThumbnails    *bool    `json:"scanGenerateThumbnails,omitempty"`
	ScanGenerateClipPreviews  *bool    `json:"scanGenerateClipPreviews,omitempty"`
}

type StashPerformer struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	AliasList  []string `json:"aliasList"`
	Favorite   bool     `json:"favorite"`
	SceneCount int      `json:"sceneCount"`
	Followed   bool     `json:"followed"`
}

type StashSettings struct {
	Configured       bool   `json:"configured"`
	Enabled          bool   `json:"enabled"`
	URL              string `json:"url"`
	APIKeyConfigured bool   `json:"apiKeyConfigured"`
	LibraryPath      string `json:"libraryPath"`
}

type SystemSettings struct {
	AppVersion string `json:"appVersion"`
}

type Task struct {
	ID                 string             `json:"id"`
	Query              string             `json:"query"`
	Status             string             `json:"status"`
	Candidate          *DownloadCandidate `json:"candidate"`
	TorrentURL         string             `json:"torrentUrl"`
	SavePath           string             `json:"savePath"`
	Category           string             `json:"category"`
	Tags               string             `json:"tags"`
	TorrentHash        string             `json:"torrentHash"`
	TorrentName        string             `json:"torrentName"`
	Progress           float64            `json:"progress"`
	QbittorrentState   string             `json:"qbittorrentState"`
	ContentPath        string             `json:"contentPath"`
	CompletedAt        *string            `json:"completedAt,omitempty"`
	StashJobID         string             `json:"stashJobId"`
	StashScanStatus    string             `json:"stashScanStatus"`
	StashScanError     string             `json:"stashScanError"`
	StashScanStartedAt *string            `json:"stashScanStartedAt,omitempty"`
	Error              string             `json:"error"`
	CreatedAt          string             `json:"createdAt"`
	UpdatedAt          string             `json:"updatedAt"`
}

type TaskSettings struct {
	Store                       string `json:"store"`
	JSONPath                    string `json:"jsonPath"`
	ProgressSyncIntervalSeconds int    `json:"progressSyncIntervalSeconds"`
	ProgressSyncEnabled         bool   `json:"progressSyncEnabled"`
}

type UpdateJackettSettingsInput struct {
	URL    string  `json:"url"`
	APIKey *string `json:"apiKey,omitempty"`
}

type UpdateQBittorrentSettingsInput struct {
	URL             string  `json:"url"`
	Username        string  `json:"username"`
	Password        *string `json:"password,omitempty"`
	DefaultSavePath string  `json:"defaultSavePath"`
	Category        string  `json:"category"`
	Tags            string  `json:"tags"`
}

type UpdateStashSettingsInput struct {
	URL         string  `json:"url"`
	APIKey      *string `json:"apiKey,omitempty"`
	LibraryPath string  `json:"libraryPath"`
}
