// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DownloadCandidate struct {
	Title     string `json:"title"`
	Tracker   string `json:"tracker"`
	InfoHash  string `json:"infoHash"`
	Link      string `json:"link"`
	MagnetURI string `json:"magnetUri"`
	Size      int64  `json:"size"`
	Seeders   int    `json:"seeders"`
	Peers     int    `json:"peers"`
}

type DownloadMediaInput struct {
	Query      string   `json:"query"`
	Trackers   []string `json:"trackers,omitempty"`
	Categories []int    `json:"categories,omitempty"`
	Limit      *int     `json:"limit,omitempty"`
	SavePath   *string  `json:"savePath,omitempty"`
	Category   *string  `json:"category,omitempty"`
	Tags       *string  `json:"tags,omitempty"`
	Paused     *bool    `json:"paused,omitempty"`
}

// Basic service health
type Health struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

type JackettSearchInput struct {
	Query      string   `json:"query"`
	Trackers   []string `json:"trackers,omitempty"`
	Categories []int    `json:"categories,omitempty"`
	Limit      *int     `json:"limit,omitempty"`
}

type JackettSearchResult struct {
	Title        string `json:"title"`
	Size         int64  `json:"size"`
	Seeders      int    `json:"seeders"`
	Peers        int    `json:"peers"`
	Tracker      string `json:"tracker"`
	TrackerID    string `json:"trackerId"`
	CategoryDesc string `json:"categoryDesc"`
	PublishDate  string `json:"publishDate"`
	Details      string `json:"details"`
	Link         string `json:"link"`
	MagnetURI    string `json:"magnetUri"`
}

type Mutation struct {
}

type QBTorrent struct {
	Hash     string  `json:"hash"`
	Name     string  `json:"name"`
	Progress float64 `json:"progress"`
	State    string  `json:"state"`
	Dlspeed  int64   `json:"dlspeed"`
	Upspeed  int64   `json:"upspeed"`
	Size     int64   `json:"size"`
	Eta      int64   `json:"eta"`
	Category string  `json:"category"`
	Tags     string  `json:"tags"`
	AddedOn  int64   `json:"addedOn"`
}

type QBittorrentAddInput struct {
	URL      string  `json:"url"`
	SavePath *string `json:"savePath,omitempty"`
	Category *string `json:"category,omitempty"`
	Tags     *string `json:"tags,omitempty"`
	Paused   *bool   `json:"paused,omitempty"`
}

type Query struct {
}

type StashJob struct {
	ID          string   `json:"id"`
	Status      string   `json:"status"`
	Description string   `json:"description"`
	Progress    *float64 `json:"progress,omitempty"`
	StartTime   *string  `json:"startTime,omitempty"`
	EndTime     *string  `json:"endTime,omitempty"`
	AddTime     string   `json:"addTime"`
	Error       *string  `json:"error,omitempty"`
	SubTasks    []string `json:"subTasks,omitempty"`
}

type StashMetadataScanInput struct {
	Paths                     []string `json:"paths,omitempty"`
	Rescan                    *bool    `json:"rescan,omitempty"`
	ScanGenerateCovers        *bool    `json:"scanGenerateCovers,omitempty"`
	ScanGeneratePreviews      *bool    `json:"scanGeneratePreviews,omitempty"`
	ScanGenerateImagePreviews *bool    `json:"scanGenerateImagePreviews,omitempty"`
	ScanGenerateSprites       *bool    `json:"scanGenerateSprites,omitempty"`
	ScanGeneratePhashes       *bool    `json:"scanGeneratePhashes,omitempty"`
	ScanGenerateThumbnails    *bool    `json:"scanGenerateThumbnails,omitempty"`
	ScanGenerateClipPreviews  *bool    `json:"scanGenerateClipPreviews,omitempty"`
}

type Task struct {
	ID               string             `json:"id"`
	Query            string             `json:"query"`
	Status           string             `json:"status"`
	Candidate        *DownloadCandidate `json:"candidate"`
	TorrentURL       string             `json:"torrentUrl"`
	SavePath         string             `json:"savePath"`
	Category         string             `json:"category"`
	Tags             string             `json:"tags"`
	TorrentHash      string             `json:"torrentHash"`
	TorrentName      string             `json:"torrentName"`
	Progress         float64            `json:"progress"`
	QbittorrentState string             `json:"qbittorrentState"`
	ContentPath      string             `json:"contentPath"`
	CompletedAt      *string            `json:"completedAt,omitempty"`
	Error            string             `json:"error"`
	CreatedAt        string             `json:"createdAt"`
	UpdatedAt        string             `json:"updatedAt"`
}
