// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type DashboardStats struct {
	Total        int `json:"total"`
	Active       int `json:"active"`
	Completed    int `json:"completed"`
	Downloading  int `json:"downloading"`
	PendingScans int `json:"pendingScans"`
	Failed       int `json:"failed"`
}

type DownloadCandidate struct {
	Title     string `json:"title"`
	Tracker   string `json:"tracker"`
	InfoHash  string `json:"infoHash"`
	Link      string `json:"link"`
	MagnetURI string `json:"magnetUri"`
	Size      int64  `json:"size"`
	Seeders   int    `json:"seeders"`
	Peers     int    `json:"peers"`
}

type DownloadMediaInput struct {
	Query      string   `json:"query"`
	Trackers   []string `json:"trackers,omitempty"`
	Categories []int    `json:"categories,omitempty"`
	Limit      *int     `json:"limit,omitempty"`
	SavePath   *string  `json:"savePath,omitempty"`
	Category   *string  `json:"category,omitempty"`
	Tags       *string  `json:"tags,omitempty"`
	Paused     *bool    `json:"paused,omitempty"`
}

// Basic service health
type Health struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

type JackettSearchInput struct {
	Query      string   `json:"query"`
	Trackers   []string `json:"trackers,omitempty"`
	Categories []int    `json:"categories,omitempty"`
	Limit      *int     `json:"limit,omitempty"`
}

type JackettSearchResult struct {
	Title        string `json:"title"`
	Size         int64  `json:"size"`
	Seeders      int    `json:"seeders"`
	Peers        int    `json:"peers"`
	Tracker      string `json:"tracker"`
	TrackerID    string `json:"trackerId"`
	CategoryDesc string `json:"categoryDesc"`
	PublishDate  string `json:"publishDate"`
	Details      string `json:"details"`
	Link         string `json:"link"`
	MagnetURI    string `json:"magnetUri"`
}

type JackettSettings struct {
	Configured       bool   `json:"configured"`
	Enabled          bool   `json:"enabled"`
	URL              string `json:"url"`
	APIKeyConfigured bool   `json:"apiKeyConfigured"`
	// Currently configured Jackett API key. Returned in plaintext for the settings UI; never logged.
	APIKey string `json:"apiKey"`
}

type LogEntry struct {
	Time    string   `json:"time"`
	Level   LogLevel `json:"level"`
	Message string   `json:"message"`
}

type LoggingSettings struct {
	Level            string `json:"level"`
	FilePath         string `json:"filePath"`
	MaxEntries       int    `json:"maxEntries"`
	MaxFileSizeBytes int    `json:"maxFileSizeBytes"`
	MaxFileBackups   int    `json:"maxFileBackups"`
}

type Mutation struct {
}

type QBTorrent struct {
	Hash     string  `json:"hash"`
	Name     string  `json:"name"`
	Progress float64 `json:"progress"`
	State    string  `json:"state"`
	Dlspeed  int64   `json:"dlspeed"`
	Upspeed  int64   `json:"upspeed"`
	Size     int64   `json:"size"`
	Eta      int64   `json:"eta"`
	Category string  `json:"category"`
	Tags     string  `json:"tags"`
	AddedOn  int64   `json:"addedOn"`
}

type QBittorrentAddInput struct {
	URL      string  `json:"url"`
	SavePath *string `json:"savePath,omitempty"`
	Category *string `json:"category,omitempty"`
	Tags     *string `json:"tags,omitempty"`
	Paused   *bool   `json:"paused,omitempty"`
}

type QBittorrentSettings struct {
	Configured         bool   `json:"configured"`
	Enabled            bool   `json:"enabled"`
	URL                string `json:"url"`
	Username           string `json:"username"`
	UsernameConfigured bool   `json:"usernameConfigured"`
	PasswordConfigured bool   `json:"passwordConfigured"`
	// Currently configured qBittorrent password. Returned in plaintext for the settings UI; never logged.
	Password        string `json:"password"`
	DefaultSavePath string `json:"defaultSavePath"`
	Category        string `json:"category"`
	Tags            string `json:"tags"`
}

type Query struct {
}

type Settings struct {
	Stash        *StashSettings        `json:"stash"`
	Jackett      *JackettSettings      `json:"jackett"`
	Qbittorrent  *QBittorrentSettings  `json:"qbittorrent"`
	Tasks        *TaskSettings         `json:"tasks"`
	Subscription *SubscriptionSettings `json:"subscription"`
	Logging      *LoggingSettings      `json:"logging"`
	System       *SystemSettings       `json:"system"`
}

type StashBoxEndpoint struct {
	Name             string `json:"name"`
	Endpoint         string `json:"endpoint"`
	APIKeyConfigured bool   `json:"apiKeyConfigured"`
}

type StashJob struct {
	ID          string   `json:"id"`
	Status      string   `json:"status"`
	Description string   `json:"description"`
	Progress    *float64 `json:"progress,omitempty"`
	StartTime   *string  `json:"startTime,omitempty"`
	EndTime     *string  `json:"endTime,omitempty"`
	AddTime     string   `json:"addTime"`
	Error       *string  `json:"error,omitempty"`
	SubTasks    []string `json:"subTasks,omitempty"`
}

type StashMetadataScanInput struct {
	Paths                     []string `json:"paths,omitempty"`
	Rescan                    *bool    `json:"rescan,omitempty"`
	ScanGenerateCovers        *bool    `json:"scanGenerateCovers,omitempty"`
	ScanGeneratePreviews      *bool    `json:"scanGeneratePreviews,omitempty"`
	ScanGenerateImagePreviews *bool    `json:"scanGenerateImagePreviews,omitempty"`
	ScanGenerateSprites       *bool    `json:"scanGenerateSprites,omitempty"`
	ScanGeneratePhashes       *bool    `json:"scanGeneratePhashes,omitempty"`
	ScanGenerateThumbnails    *bool    `json:"scanGenerateThumbnails,omitempty"`
	ScanGenerateClipPreviews  *bool    `json:"scanGenerateClipPreviews,omitempty"`
}

type StashPerformer struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	AliasList  []string `json:"aliasList"`
	Favorite   bool     `json:"favorite"`
	ImagePath  *string  `json:"imagePath,omitempty"`
	SceneCount int      `json:"sceneCount"`
	Subscribed bool     `json:"subscribed"`
}

type StashPerformerConnection struct {
	Items       []*StashPerformer `json:"items"`
	Page        int               `json:"page"`
	PageSize    int               `json:"pageSize"`
	TotalCount  int               `json:"totalCount"`
	TotalPages  int               `json:"totalPages"`
	HasPrevPage bool              `json:"hasPrevPage"`
	HasNextPage bool              `json:"hasNextPage"`
}

type StashSettings struct {
	Configured       bool   `json:"configured"`
	Enabled          bool   `json:"enabled"`
	URL              string `json:"url"`
	APIKeyConfigured bool   `json:"apiKeyConfigured"`
	// Currently configured Stash API key. Returned in plaintext for the settings UI; never logged.
	APIKey      string `json:"apiKey"`
	LibraryPath string `json:"libraryPath"`
}

type SubscribedPerformer struct {
	Performer             *StashPerformer        `json:"performer"`
	LastCheckedAt         *string                `json:"lastCheckedAt,omitempty"`
	LastError             *string                `json:"lastError,omitempty"`
	PendingReleaseCount   int                    `json:"pendingReleaseCount"`
	ProcessedReleaseCount int                    `json:"processedReleaseCount"`
	RecentReleases        []*SubscriptionRelease `json:"recentReleases"`
}

type SubscriptionRelease struct {
	Key    string  `json:"key"`
	Source string  `json:"source"`
	Title  string  `json:"title"`
	Code   *string `json:"code,omitempty"`
	Date   *string `json:"date,omitempty"`
	URL    *string `json:"url,omitempty"`
	Query  string  `json:"query"`
	TaskID *string `json:"taskID,omitempty"`
	SeenAt string  `json:"seenAt"`
}

type SubscriptionSettings struct {
	Store               string `json:"store"`
	DbPath              string `json:"dbPath"`
	PollIntervalSeconds int    `json:"pollIntervalSeconds"`
	PollEnabled         bool   `json:"pollEnabled"`
	// Stash Box instances currently configured inside the Stash server.
	StashBoxes []*StashBoxEndpoint `json:"stashBoxes"`
	// Endpoint URLs in the user-defined order used for subscription lookups. Endpoints not listed here are still queried, in their Stash order, appended after the listed ones. An empty list means use Stash's order as-is.
	StashBoxEndpoints []string `json:"stashBoxEndpoints"`
	// Whether the last attempt to load Stash Box endpoints from Stash succeeded.
	StashBoxesLoaded bool `json:"stashBoxesLoaded"`
	// Reason for the most recent Stash Box load failure. Null when stashBoxesLoaded is true.
	StashBoxesLoadError *string `json:"stashBoxesLoadError,omitempty"`
}

type SystemSettings struct {
	AppVersion string `json:"appVersion"`
}

type Task struct {
	ID                 string             `json:"id"`
	Query              string             `json:"query"`
	Status             string             `json:"status"`
	Candidate          *DownloadCandidate `json:"candidate"`
	TorrentURL         string             `json:"torrentUrl"`
	SavePath           string             `json:"savePath"`
	Category           string             `json:"category"`
	Tags               string             `json:"tags"`
	TorrentHash        string             `json:"torrentHash"`
	TorrentName        string             `json:"torrentName"`
	Progress           float64            `json:"progress"`
	QbittorrentState   string             `json:"qbittorrentState"`
	ContentPath        string             `json:"contentPath"`
	CompletedAt        *string            `json:"completedAt,omitempty"`
	StashJobID         string             `json:"stashJobId"`
	StashScanStatus    string             `json:"stashScanStatus"`
	StashScanError     string             `json:"stashScanError"`
	StashScanStartedAt *string            `json:"stashScanStartedAt,omitempty"`
	Error              string             `json:"error"`
	CreatedAt          string             `json:"createdAt"`
	UpdatedAt          string             `json:"updatedAt"`
}

type TaskSettings struct {
	Store                       string `json:"store"`
	DbPath                      string `json:"dbPath"`
	ProgressSyncIntervalSeconds int    `json:"progressSyncIntervalSeconds"`
	ProgressSyncEnabled         bool   `json:"progressSyncEnabled"`
}

type UpdateJackettSettingsInput struct {
	URL    string  `json:"url"`
	APIKey *string `json:"apiKey,omitempty"`
}

type UpdateLoggingSettingsInput struct {
	Level            string `json:"level"`
	FilePath         string `json:"filePath"`
	MaxEntries       int    `json:"maxEntries"`
	MaxFileSizeBytes int    `json:"maxFileSizeBytes"`
	MaxFileBackups   int    `json:"maxFileBackups"`
}

type UpdateQBittorrentSettingsInput struct {
	URL             string  `json:"url"`
	Username        string  `json:"username"`
	Password        *string `json:"password,omitempty"`
	DefaultSavePath string  `json:"defaultSavePath"`
	Category        string  `json:"category"`
	Tags            string  `json:"tags"`
}

type UpdateStashSettingsInput struct {
	URL         string  `json:"url"`
	APIKey      *string `json:"apiKey,omitempty"`
	LibraryPath string  `json:"libraryPath"`
}

type UpdateSubscriptionSettingsInput struct {
	Store               string `json:"store"`
	DbPath              string `json:"dbPath"`
	PollIntervalSeconds int    `json:"pollIntervalSeconds"`
	// See SubscriptionSettings.stashBoxEndpoints.
	StashBoxEndpoints []string `json:"stashBoxEndpoints"`
}

type LogLevel string

const (
	LogLevelDebug   LogLevel = "Debug"
	LogLevelInfo    LogLevel = "Info"
	LogLevelWarning LogLevel = "Warning"
	LogLevelError   LogLevel = "Error"
)

var AllLogLevel = []LogLevel{
	LogLevelDebug,
	LogLevelInfo,
	LogLevelWarning,
	LogLevelError,
}

func (e LogLevel) IsValid() bool {
	switch e {
	case LogLevelDebug, LogLevelInfo, LogLevelWarning, LogLevelError:
		return true
	}
	return false
}

func (e LogLevel) String() string {
	return string(e)
}

func (e *LogLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogLevel", str)
	}
	return nil
}

func (e LogLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LogLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LogLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
